# -*- coding: utf-8 -*-
"""二種実践演習 batch27：261〜270問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "261",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;公社債投信;投資信託;standard",
        "stem": "公社債投信は、公社債を主な投資対象とする投資信託である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "公社債投信は債券型投信で、国債直接保有とは間接投資として区別します。",
        "explanation_summary": "公社債投信＝債券型投信。",
        "explanation_correct": "正答は「正しい」です。公社債投信は、国債・地方債等の公社債を主な投資対象とする投資信託です。受益権を取得する間接投資であり、元本保証はありません。第31問の国債・第9問の投資信託と接続します",
        "explanation_point": "公社債投信・国債・受益権を「直接投資／間接投資」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "262",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;ノーロード投信;投資信託;standard",
        "stem": "ノーロード投信は、購入時手数料も信託報酬も一切かからない。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "ノーロードは購入時手数料がない投信で、信託報酬等のコストは発生します。",
        "explanation_summary": "ノーロード≠無コスト。",
        "explanation_correct": "正答は「誤っている」です。ノーロード投信は、購入時手数料（フロントロード）がかからない投資信託です。信託報酬（運用管理費用）等のコストは発生し、手数料・報酬が一切ないわけではありません",
        "explanation_point": "ノーロード投信・信託報酬・販売手数料をコスト構造の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "263",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;裁定取引;日経225先物;standard",
        "stem": "裁定取引は、現物と先物等の価格差を利用する売買である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "裁定取引は現物市場と先物市場の価格差（ベーシス）を利用する手法です。",
        "explanation_summary": "裁定＝現物＋先物。",
        "explanation_correct": "正答は「正しい」です。裁定取引は、同一原資産の現物と先物（または関連商品）の価格差を利用して行う裁定売買です。日経225先物と上場株式の組み合わせが典型例で、第251問の日経225先物・第217問の先物取引と接続します",
        "explanation_point": "裁定取引・日経225先物・上場株式を「現物／先物／価格差」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "264",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;アルゴリズム取引;SOR;standard",
        "stem": "アルゴリズム取引は、コンピュータプログラムに基づき自動的に売買を行う取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "アルゴ取引はプログラムによる自動売買で、リスク管理・最良執行と接点があります。",
        "explanation_summary": "アルゴ＝自動売買。",
        "explanation_correct": "正答は「正しい」です。アルゴリズム取引（アルゴ取引）は、コンピュータプログラムに基づき自動的に売買を行う取引です。第176問のSOR・第196問のリスク管理と接続し、暴走防止等のリスク管理体制が求められます",
        "explanation_point": "アルゴリズム取引・SOR・リスク管理を3列比較表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "265",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;ディスクロージャー;目論見書;standard",
        "stem": "ディスクロージャーは、企業や金融商品の情報を開示することである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "ディスクロージャーは情報開示の総称で、目論見書等はその具体手段です。",
        "explanation_summary": "開示＝総称。",
        "explanation_correct": "正答は「正しい」です。ディスクロージャー（disclosure）は、企業や金融商品に関する情報を開示し、投資家の適正な判断を支援することをいいます。目論見書・有価証券報告書・重要事項説明等は具体手段です",
        "explanation_point": "ディスクロージャー・目論見書・重要事項説明を「概念／手段」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "266",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;ラップ口座;投資一任契約;standard",
        "stem": "ラップ口座は、投資助言契約と同一で最終判断は顧客にある。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "ラップ口座は投資一任契約に基づき運用判断を委託者に一任する商品です。",
        "explanation_summary": "ラップ＝一任型。",
        "explanation_correct": "正答は「誤っている」です。ラップ口座は、投資一任契約に基づき個別に運用する口座型商品で、運用判断は委託者（運用者）に一任されます。投資助言契約は最終判断が顧客にあり、同一ではありません。第155問の投資一任契約・第174問の投資助言契約と接続します",
        "explanation_point": "ラップ口座・投資一任契約・投資助言契約を「誰が判断するか」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "267",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;株式分割の事前開示;適時開示;standard",
        "stem": "株式分割の事前開示は、株式分割決議後に速やかに行う適時開示義務である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "株式分割決議後は分割比率等を速やかに適時開示する義務があります。",
        "explanation_summary": "分割決議→速やか開示。",
        "explanation_correct": "正答は「正しい」です。株式分割の事前開示は、上場会社が株式分割を決議した際、分割比率・効力発生日等を速やかに開示する適時開示義務です。第32問の株式分割・第46問の適時開示と接続します",
        "explanation_point": "株式分割・適時開示・臨時報告書を開示フロー図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "268",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;第二種少額電子募集取扱業;第二種金融商品取引業;standard",
        "stem": "第二種少額電子募集取扱業は、少額の電子募集取扱を媒介する第二種業である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "第二種少額電子募集取扱業は媒介に限定され、取扱は第一種少額側です。",
        "explanation_summary": "第二種少額＝媒介。",
        "explanation_correct": "正答は「正しい」です。第二種少額電子募集取扱業は、インターネット等を用いた少額の電子募集取扱を媒介する第二種金融商品取引業です。取扱ではなく媒介に限定され、第15問の第二種金融商品取引業と登録業務が異なります",
        "explanation_point": "第一種少額・第二種少額・第二種業を「取扱／媒介」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "269",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;株主代表訴訟;株式;standard",
        "stem": "株主代表訴訟は、株主が会社に代わり役員等の責任を追及する訴訟である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "株主代表訴訟は会社法上の株主提訴制度で、会社自身の提訴とは別です。",
        "explanation_summary": "株主代表＝株主提訴。",
        "explanation_correct": "正答は「正しい」です。株主代表訴訟は、会社が役員等を訴えない場合に、株主が会社のために提訴する会社法上の制度です。第2問の株式・第35問の相場操縦（不公正取引）とは民事責任追及の枠組みが異なります",
        "explanation_point": "株主代表訴訟・議決権・株主総会を株主権の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "270",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;オペレーショナルリスク;リスク管理;standard",
        "stem": "オペレーショナルリスクは、株価変動による損失リスクである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "オペレーショナルリスクは業務プロセス・人・システムの不備によるリスクです。",
        "explanation_summary": "オペレ≠市場リスク。",
        "explanation_correct": "正答は「誤っている」です。オペレーショナルリスクは、業務プロセス・人・システムの不備により損失を被るリスクです。株価変動による市場リスクとは別類型であり、第196問のリスク管理・第256問のSTPと接続します",
        "explanation_point": "市場リスク・信用リスク・オペレーショナルリスクを4類型表にしてみましょう。",
        "explanation_choices": "",
    },
]
