# -*- coding: utf-8 -*-
"""二種実践演習 batch26：251〜260問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "251",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;日経225先物;先物取引;standard",
        "stem": "日経225先物は、日経平均株価を原資産とする株価指数先物である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "日経225先物は指数を原資産とする先物で、個別株先物やオプションとは別です。",
        "explanation_summary": "日経225先物＝指数先物。",
        "explanation_correct": "正答は「正しい」です。日経225先物は、日経平均株価（Nikkei 225）を原資産とする株価指数先物で、大阪取引所等で取引されます。個別株式の先物やコール・プットオプション（権利）とは別商品です。",
        "explanation_point": "日経225先物・先物取引・値洗いを「原資産／義務／日次精算」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "252",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;値洗い;先物取引;standard",
        "stem": "値洗いは、デリバティブ取引で毎日評価損益を精算する仕組みである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "値洗いは建玉の評価損益を日次で確定し、証拠金口座に反映する仕組みです。",
        "explanation_summary": "値洗い＝日次精算。",
        "explanation_correct": "正答は「正しい」です。値洗い（マーク・トゥ・マーケット）は、先物・オプション等のデリバティブ取引で、相場変動に応じて毎日評価損益を精算する仕組みです。信用取引の保証金（追証）とは別概念として整理します。",
        "explanation_point": "値洗い・証拠金・追加証拠金をデリバ取引の日次フロー図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "253",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;市場区分;プライム市場;standard",
        "stem": "市場区分は、上場会社を業種（セクター）ごとに分類した区分である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "市場区分はプライム・スタンダード・グロース等の上場レベル分類で、業種分類とは別です。",
        "explanation_summary": "市場区分≠業種。",
        "explanation_correct": "正答は「誤っている」です。市場区分は、上場会社を流動性・ガバナンス等に応じて分類した区分で、2022年4月再編後はプライム・スタンダード・グロースの3区分です。業種（セクター）分類とは別概念であり、第162問のプライム市場と接続します。",
        "explanation_point": "市場区分・プライム市場・業種分類を2列比較表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "254",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;ブロックトレード;立会外分売;standard",
        "stem": "ブロックトレードは、大口の有価証券を一括して売買する取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "ブロックトレードは大口一括執行で、市場への価格影響を抑える手法です。",
        "explanation_summary": "ブロック＝大口一括。",
        "explanation_correct": "正答は「正しい」です。ブロックトレードは、大口の有価証券を一括して売買する取引で、板に大量注文を出すことによる価格影響を抑える目的があります。第245問の立会外分売・VWAPと大口執行手法として接続します。",
        "explanation_point": "ブロックトレード・立会外分売・VWAPを「一括か時間外か」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "255",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;VWAP;最良執行;standard",
        "stem": "VWAPは、一定期間の単純平均価格である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "VWAPは出来高で加重した平均価格で、執行品質のベンチマークに使われます。",
        "explanation_summary": "VWAP＝出来高加重。",
        "explanation_correct": "正答は「誤っている」です。VWAP（Volume Weighted Average Price）は、一定期間の取引量で加重した出来高加重平均価格です。単純平均価格とは計算方法が異なり、大口執行の執行品質評価のベンチマークとして用いられます。",
        "explanation_point": "VWAP・最良執行の原則・ブロックトレードを執行品質の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "256",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;STP;バックオフィス;standard",
        "stem": "STPは、注文から決済まで業務を自動化する仕組みである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "STPはフロントからバックオフィスまで人手を介さず直通処理する方式です。",
        "explanation_summary": "STP＝直通自動化。",
        "explanation_correct": "正答は「正しい」です。STP（Straight Through Processing／ストレート・スルー・プロセシング）は、受注から約定・受渡・簿記まで人手を介さず業務を自動化する仕組みです。フロント業務のみでなくバックオフィスを含みます。",
        "explanation_point": "STP・約定・受渡・バックオフィスを業務フロー図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "257",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;書面の交付又は電磁的方法による提供;重要事項説明;standard",
        "stem": "書面の交付又は電磁的方法による提供は、口頭説明のみで足りる。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "原則書面交付、条件を満たせば電磁的方法も可能で、口頭のみでは足りません。",
        "explanation_summary": "口頭のみでは不可。",
        "explanation_correct": "正答は「誤っている」です。書面の交付又は電磁的方法による提供は、顧客への情報提供を書面で交付するか、条件を満たせば電磁的方法で提供する法定要件です。口頭説明のみでは足りず、第10問の契約締結前交付書面・第37条重要事項説明と接続します。",
        "explanation_point": "書面交付・電磁的方法・重要事項説明を情報提供の3手段表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "258",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;基準日;配当;standard",
        "stem": "基準日は、配当・議決権等の株主権利を確定する日である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "基準日当日に株主名簿に記載された者が権利者となります。",
        "explanation_summary": "基準日＝権利確定。",
        "explanation_correct": "正答は「正しい」です。基準日は、配当・議決権等の株主権利を確定する基準となる日です。基準日当日に株主名簿に記載された者が権利者となり、権利付き最終日（2営業日前）とは区別します。",
        "explanation_point": "基準日・権利付き最終日・配当を権利確定のタイムラインにしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "259",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;電子公告;適時開示;standard",
        "stem": "電子公告は、有価証券報告書と同一の開示制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "電子公告は会社法上の公告、有価証券報告書は金商法上の継続開示です。",
        "explanation_summary": "公告≠金商法開示。",
        "explanation_correct": "正答は「誤っている」です。電子公告は、インターネットを用いた会社法上の公告方法です。有価証券報告書は金商法上の継続開示制度であり、根拠法令・目的が異なります。第46問の適時開示とも区別します。",
        "explanation_point": "電子公告・有価証券報告書・適時開示を「会社法／金商法」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "260",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;内部統制システム;コンプライアンス;standard",
        "stem": "内部統制システムが整っていれば、コンプライアンス違反は起こらない。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "内部統制は違反リスクを下げる仕組みであり、100％防止を保証するものではありません。",
        "explanation_summary": "内部統制≠違反ゼロ。",
        "explanation_correct": "正答は「誤っている」です。内部統制システムは、財務報告の信頼性・法令遵守等を確保するための組織・手続・人・システムの総体です。整備・運用・評価を継続する仕組みであり、違反が100％起きないことを保証するものではありません。第38問のコンプライアンス・第158問の内部統制報告書と接続します。",
        "explanation_point": "内部統制システム・コンプライアンス・内部統制報告書を「設計／運用／評価」の表にしてみましょう。",
        "explanation_choices": "",
    },
]
