# -*- coding: utf-8 -*-
"""二種実践演習 batch15：141〜150問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "141",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;上場株式;新規公開;standard",
        "stem": "上場株式は、金融商品取引所に上場し公開市場で売買される株式である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "上場株式は取引所の公開市場で売買され、継続開示等の論点が試験に出ます。",
        "explanation_summary": "上場株＝公開市場で売買。",
        "explanation_correct": "正答は「正しい」です。上場株式は、金融商品取引所に上場し、公開市場で売買される株式会社の株式です。上場後は継続的開示義務が発行者に課され、原則単元株式数単位で売買されます。非上場株とは流動性・開示の面で異なります",
        "explanation_point": "上場株式と非上場株を、売買の場・開示義務の2列で比較表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "142",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;株主名簿;議決権;standard",
        "stem": "株主名簿は、投資信託の受益人名簿と同一である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "株主名簿は株式会社の株主管理帳簿で、投信の受益人名簿とは別物です。",
        "explanation_summary": "株主名簿≠受益人名簿。",
        "explanation_correct": "正答は「誤っている」です。株主名簿は、株式会社が作成・備置する株主の氏名・住所等を記載した名簿で、議決権行使・配当支払い等に用いられます。投資信託の受益人名簿とは別の帳簿であり、同一ではありません",
        "explanation_point": "第112問の議決権・第113問の株主総会と合わせ、株主名簿の役割を1行で説明してみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "143",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;オプション取引;先物取引;standard",
        "stem": "オプション取引は、将来の原資産の売買義務を負う取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "オプションは権利の売買で、先物の義務取引とは性質が異なります。",
        "explanation_summary": "OP＝権利の売買。",
        "explanation_correct": "正答は「誤っている」です。オプション取引は、将来一定期日までに原資産を買う権利（コール）または売る権利（プット）を取引するデリバティブ取引です。権利行使か放棄かを選択でき、第123問の先物取引（義務の売買）とは性質が異なります",
        "explanation_point": "第123問の先物と並べ、「義務か権利か」を声に出して対比してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "144",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;一般信用取引;制度信用取引;standard",
        "stem": "一般信用取引は、証券会社が個別に貸株を調達して行う信用取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "一般信用は個別貸株調達、制度信用は取引所制度に基づく標準型です。",
        "explanation_summary": "一般信用＝個別貸株調達。",
        "explanation_correct": "正答は「正しい」です。一般信用取引は、証券会社が個別に貸株を調達して行う信用取引です。第135問の制度信用取引（取引所の制度に基づく標準型）と対比され、貸株料・品貸料の交渉等が論点となります",
        "explanation_point": "制度信用と一般信用を、貸株の調達方法の1列で比較表にしてみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "145",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;投資助言業;投資一任契約;standard",
        "stem": "投資助言業において、最終的な売買判断は顧客が行う。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "助言業は助言のみで、一任業のように判断を委任するものではありません。",
        "explanation_summary": "助言業＝判断は顧客。",
        "explanation_correct": "正答は「正しい」です。投資助言業は、投資判断の助言を業として行う金融商品取引業です。助言を提供しますが、最終的な売買判断は顧客が行います。投資一任契約（判断まで委任）や金融商品仲介業（三者間の媒介）とは区別します",
        "explanation_point": "助言業・一任業・仲介業を「誰が最終判断するか」の1列で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "146",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;店頭売買;店頭有価証券;standard",
        "stem": "店頭売買は、金融商品取引所の市場で行われる売買取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "店頭売買は取引所以外（OTC）での売買で、上場市場取引とは別です。",
        "explanation_summary": "店頭＝取引所以外。",
        "explanation_correct": "正答は「誤っている」です。店頭売買とは、金融商品取引所の市場以外で行われる有価証券等の売買取引をいいます。上場株式の市場取引とは場所が異なり、店頭有価証券やPTS取引等と関連します",
        "explanation_point": "上場市場・店頭売買・PTSを、売買の場の3行で書き分けてみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "147",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;少額公募;私募;standard",
        "stem": "少額公募は、私募と同一の制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "少額公募は小口向け公募で簡易届出、私募は不特定多数への勧誘制限がある別制度です。",
        "explanation_summary": "少額公募≠私募。",
        "explanation_correct": "正答は「誤っている」です。少額公募は、一定額以下の小口向け公募で、通常の公募より簡易な届出手続が認められる制度です。私募（少人数私募等）は不特定多数への勧誘を制限する発行形態であり、同一の制度ではありません",
        "explanation_point": "公募・私募・少額公募・みなし公募を発行形態の分岐図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "148",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;登録金融機関;第一種金融商品取引業;standard",
        "stem": "登録金融機関は、第一種金融商品取引業者と完全に同一の業態である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "登録金機は銀行等の登録で業務範囲に制限があり、証券会社の第一種業とは異なります。",
        "explanation_summary": "登録金機≠第一種業者。",
        "explanation_correct": "正答は「誤っている」です。登録金融機関は、銀行・信託銀行等が証券業務を行うため金商法に登録した機関です。第一種金融商品取引業者（証券会社）とは登録の種類・業務範囲・取扱商品に制限があり、完全に同一の業態ではありません",
        "explanation_point": "証券会社・登録金機・第二種業者を、登録種別と業務範囲の2列で比較してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "149",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;半期報告書;継続開示;standard",
        "stem": "半期報告書は、四半期報告書制度の導入により廃止された継続開示書類である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "半期報告書は旧制度の6か月ごとの定期開示で、現行は四半期報告書が中心です。",
        "explanation_summary": "半期報告書＝旧制度・廃止。",
        "explanation_correct": "正答は「正しい」です。半期報告書は、上場会社等が半期ごとに提出していた継続開示書類ですが、四半期報告書制度の導入により廃止されました。試験では半期（6か月）と四半期（3か月）の頻度差、現行の定期開示体系を整理することが論点です",
        "explanation_point": "第127問の四半期報告書と合わせ、半期（旧）・四半期（現行）・有報（年次）を整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "150",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;顧客分別金信託;信託保全;standard",
        "stem": "顧客分別金信託の受益者は、顧客である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "顧客金銭を信託して保全する方式で、受益者は顧客です。",
        "explanation_summary": "分別金信託＝受益者は顧客。",
        "explanation_correct": "正答は「正しい」です。顧客分別金信託は、顧客の金銭を信託銀行等に信託して保全する方式で、受益者は顧客です。業者の固有財産と分離して保護する信託保全の具体手段であり、第110問の合算禁止・第120問の分別管理とあわせて顧客資産保護の柱です",
        "explanation_point": "合算禁止・顧客分別金信託・有価証券の分別管理を、対象資産別に3行で整理してみましょう。",
        "explanation_choices": "",
    },
]
