# -*- coding: utf-8 -*-
"""二種実践演習 batch24：231〜240問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "231",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;MBO;TOB;standard",
        "stem": "MBOは経営陣が主導する買収で、非公開化を伴うことが多い。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "MBOはManagement Buy-Outの略で、経営陣主導の買収・非公開化が典型です。",
        "explanation_summary": "MBO＝経営陣買収。",
        "explanation_correct": "正答は「正しい」です。MBO（Management Buy-Out）は、経営陣が主導して対象会社の株式を買い集める買収手法で、上場廃止（非公開化）を伴うことが多いです。新規公開（IPO）とは目的が異なり、公開買付け（TOB）を利用する場合もあります",
        "explanation_point": "MBO・TOB・新規公開を「初上場か買収か・誰が主導か」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "232",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;ストックオプション;コールオプション;standard",
        "stem": "ストックオプションは、取引所のコールオプションと同一の制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "SOは会社付与の新株予約権、Callは市場のデリバティブで別制度です。",
        "explanation_summary": "SO≠Call。",
        "explanation_correct": "正答は「誤っている」です。ストックオプション（SO）は、会社が役員・従業員等に付与する新株予約権の一類型です。取引所のコールオプションはデリバティブ市場の商品であり、発行主体・法的枠組みが異なります。第221問のコールオプション・新株予約権と3列比較表で整理します",
        "explanation_point": "SO・新株予約権・Callを「誰が付与するか／どこで売買するか」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "233",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;源泉徴収;特定口座;standard",
        "stem": "源泉徴収は、証券会社等が譲渡益に係る所得税等を天引きする制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "源泉徴収は支払者が税金を天引きし、特定口座（源泉あり）では確定申告が簡略化されます。",
        "explanation_summary": "源泉徴収＝天引き。",
        "explanation_correct": "正答は「正しい」です。源泉徴収は、証券会社等の支払者が、有価証券等の譲渡益に係る所得税等をあらかじめ天引きして国に納付する制度です。特定口座（源泉徴収あり）を選ぶと、損益通算のうえ源泉徴収され、原則確定申告不要にできる場合があります",
        "explanation_point": "源泉徴収・特定口座・一般口座を「誰が税金を処理するか」の1列で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "234",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;板寄せ方式;ザラバ方式;standard",
        "stem": "板寄せ方式は、板の需給バランスを見て一斉約定する方式である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "板寄せは一斉約定、ザラバは順次約定です。",
        "explanation_summary": "板寄せ＝一斉約定。",
        "explanation_correct": "正答は「正しい」です。板寄せ方式は、寄付後の通常取引時間において、板に集まった買い注文・売り注文の需給バランスを見て一斉約定する取引方式です。第224問のザラバ方式（順次約定）と対比して覚えます",
        "explanation_point": "寄付・板寄せ方式・ザラバ方式を「約定のタイミング」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "235",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;逆指値注文;指値注文;standard",
        "stem": "逆指値注文は、最初から指値価格で即時約定する注文である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "逆指値はトリガー到達後に成行・指値へ切り替わる2段構造の注文です。",
        "explanation_summary": "逆指値＝トリガー後発動。",
        "explanation_correct": "正答は「誤っている」です。逆指値注文は、あらかじめ定めたトリガー価格に達した時点で、成行または指値注文に切り替わる2段構造の注文です。最初から指値で即時約定するのは指値注文であり、同一ではありません。第195問の指値注文・第205問の成行注文と接続します",
        "explanation_point": "指値・成行・逆指値を「いつ・どの価格で発注されるか」の3段フローにしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "236",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;証券ローン;信用取引;standard",
        "stem": "証券ローンは、信用取引の株券調達に利用される有価証券の貸借取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "証券ローンは株主等から借り入れた株を信用売りの貸株原資に回す仕組みです。",
        "explanation_summary": "証券ローン＝株券調達。",
        "explanation_correct": "正答は「正しい」です。証券ローンは、有価証券の貸借取引で、証券会社等が株主等から株式を借り入れ、信用取引の信用売りに必要な株券調達に利用されます。第155問の貸株・第154問の信用取引と接続します",
        "explanation_point": "信用売り・貸株・証券ローンを「株券の流れ」の図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "237",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;適格機関投資家;特定投資家;standard",
        "stem": "適格機関投資家は、一般投資家と同一の区分である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "適格機関投資家は専門的投資家の一類型で、一般投資家とは区分が異なります。",
        "explanation_summary": "適格機関≠一般。",
        "explanation_correct": "正答は「誤っている」です。適格機関投資家は、一定の要件を満たす機関投資家に該当する専門的投資家の一類型です。一般投資家・特定投資家・プロの投資家と並ぶ投資家区分のひとつであり、一般投資家と同一ではありません。第13問の特定投資家・第33問のプロの投資家と投資家区分表で整理します",
        "explanation_point": "一般・特定・プロ・適格機関投資家を1枚の区分表に並べてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "238",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;顧客勘定;自己取引;standard",
        "stem": "顧客勘定は、自己勘定と混同して管理してもよい。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "顧客勘定と自己勘定は分離管理が原則で、混同は利益相反リスクを招きます。",
        "explanation_summary": "顧客／自己は分離。",
        "explanation_correct": "正答は「誤っている」です。顧客勘定は、金融商品取引業者が顧客の取引を記録する勘定であり、自己勘定（自己の売買）と分離して管理する必要があります。混同は利益相反や不正の温床となり、第226問の自己取引・第17問の分別管理と接続します",
        "explanation_point": "顧客勘定・自己勘定・分別管理を「帳簿／資産」の2層表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "239",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;金融商品取引業協会;日本証券業協会;standard",
        "stem": "金融商品取引業協会は、金商法上の業協会の総称である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "金融商品取引業協会は上位概念で、日本証券業協会等の認可協会を含みます。",
        "explanation_summary": "業協会＝総称。",
        "explanation_correct": "正答は「正しい」です。金融商品取引業協会は、金融商品取引法上の業協会の総称であり、認可金融商品取引業協会を含みます。日本証券業協会（第187問）はその代表例で、外務員試験の運営主体でもあります",
        "explanation_point": "金融商品取引業協会・認可協会・日本証券業協会を3層の図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "240",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;反社会的勢力との取引禁止;反社会的勢力排除;standard",
        "stem": "反社会的勢力との取引禁止は、一般顧客とのすべての取引を禁止する制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "対象は反社会的勢力との関係遮断であり、一般顧客との適正な取引は継続します。",
        "explanation_summary": "反社遮断≠全取引禁止。",
        "explanation_correct": "正答は「誤っている」です。反社会的勢力との取引禁止は、暴力団等の反社会的勢力との取引関係を持たないための義務・方針です。一般顧客との適正な取引を妨げるものではなく、第18問の反社会的勢力排除・第38問のコンプライアンスと接続します",
        "explanation_point": "反社会的勢力排除・反社会的勢力との取引禁止・本人確認を「対象／目的」の表にしてみましょう。",
        "explanation_choices": "",
    },
]
