# -*- coding: utf-8 -*-
"""二種実践演習 batch31：301〜310問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "301",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;普通株式;議決権;standard",
        "stem": "普通株式は、原則として1株1票の議決権を有する。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "普通株式は標準型の株式で、会社法上1株1票が原則です。",
        "explanation_summary": "普通株＝1株1票。",
        "explanation_correct": "正答は「正しい」です。普通株式は、株式会社が発行する標準的な株式で、議決権と残余財産分配請求権を原則として持ち、1株1票が基本です。第71問の優先株式との権利比較・第2問の株式と接続します。",
        "explanation_point": "普通株・優先株・種類株を「議決権／配当優先」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "302",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;優先株式;種類株式;standard",
        "stem": "優先株式は、定款の定めにより配当で普通株式より優先され得る種類株式である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "優先株式は配当・残余財産で普通株より優先される設計が典型です。",
        "explanation_summary": "優先株＝配当等で優先。",
        "explanation_correct": "正答は「正しい」です。優先株式は、定款の定めにより配当や残余財産の分配において普通株式より優先される種類株式です。第81問の残余財産・第71問の普通株式と接続し、「優先」の意味を配当・残余の2軸で整理します。",
        "explanation_point": "普通株・優先株を配当・残余財産・議決権の3行で比較表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "303",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;新株予約権;ストックオプション;standard",
        "stem": "ストックオプションは、新株予約権の一類型である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "SOは従業員等に付与される新株予約権の一類型で、取引所のコールオプションとは別です。",
        "explanation_summary": "SO⊂新株予約権。",
        "explanation_correct": "正答は「正しい」です。ストックオプション（SO）は、従業員等に付与される新株予約権の一類型です。新株予約権は将来の新株引受権を表示する有価証券であり、第72問の有価証券該当性と接続します。取引所のデリバティブ取引とは別制度です。",
        "explanation_point": "新株予約権・SO・取引所コールオプションを「付与元／有価証券該当」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "304",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;利益相反管理;顧客保護;standard",
        "stem": "利益相反のおそれがある取引については、顧客への開示等の管理が求められる。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "利益相反取引は一律禁止ではなく、認識・開示・管理が求められます。",
        "explanation_summary": "利益相反＝開示・管理。",
        "explanation_correct": "正答は「正しい」です。利益相反管理とは、顧客の利益と自社の利益が相反するおそれのある取引について、その旨を顧客に開示する等、適切に管理する体制をいいます。第75問の「全面禁止」誤解と対比し、在庫株販売等の典型例で整理します。",
        "explanation_point": "利益相反の認識→開示→管理の流れを1枚のフロー図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "305",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;勧誘規則;日本証券業協会;standard",
        "stem": "勧誘規則は、協会加入の金融商品取引業者に遵守義務がある。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "勧誘規則は日本証券業協会の自主規制で、加入業者に遵守義務があります。",
        "explanation_summary": "勧誘規則＝加入業者に義務。",
        "explanation_correct": "正答は「正しい」です。勧誘規則は日本証券業協会の自主規制規則で、協会加入の金融商品取引業者等に遵守義務があります。第85問の規則の位置づけ・第86問の高齢者配慮と接続し、法令と協会規則の二層構造を整理します。",
        "explanation_point": "金商法37条・40条と勧誘規則を「法令／協会規則」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "306",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;高齢者への勧誘;勧誘規則;standard",
        "stem": "高齢者への勧誘には、通常より慎重な説明・記録・配慮が求められる。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "高齢者勧誘は全面禁止ではなく、特別配慮・記録が要点です。",
        "explanation_summary": "高齢者勧誘＝特別配慮。",
        "explanation_correct": "正答は「正しい」です。高齢者への勧誘は、勧誘規則等により通常より慎重な説明・記録・配慮が求められる場面があります。第86問の「全面禁止」誤解と対比し、適合性の原則・重要事項説明も併せて必要である点を整理します。",
        "explanation_point": "高齢者勧誘で追加確認すべき3項目をリストアップしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "307",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;内部管理責任者;コンプライアンス;standard",
        "stem": "内部管理責任者は、顧客の資産を分別管理する窓口担当者である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "内管責は社内管理の責任を担う役員等で、分別管理の実務担当とは別です。",
        "explanation_summary": "内管責≠分別管理担当。",
        "explanation_correct": "正答は「誤っている」です。内部管理責任者（内管責）は、金融商品取引業者等において業務の適正を確保するため社内管理の責任を担う役員等です。顧客資産の分別管理は業務体制の一環ですが、内管責＝分別管理の窓口担当という理解は誤りです。第139問の内管責・第17問の分別管理と接続します。",
        "explanation_point": "内管責・コンプライアンス・分別管理の役割を3行で書き分けてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "308",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;説の流布;不公正取引;standard",
        "stem": "説の流布は、詐術を用いて相場を変動させる行為である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "説の流布は事実に反する風説の流布、偽計行為は詐術による相場変動です。",
        "explanation_summary": "説の流布≠偽計。",
        "explanation_correct": "正答は「誤っている」です。説の流布（風説の流布）は、事実に反する風説を流し相場に影響を与える行為です。詐術を用いて相場を変動させるのは偽計行為であり、手段が異なります。第99問の説の流布・第138問の偽計行為を「風説／詐術」で対比します。",
        "explanation_point": "説の流布・偽計行為・相場操縦を手段のキーワード1つずつで区別してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "309",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;偽計行為;不公正取引;standard",
        "stem": "偽計行為は、事実に反する風説を流す行為である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "風説の流布は説の流布、偽計行為は詐術による相場変動です。",
        "explanation_summary": "偽計≠風説の流布。",
        "explanation_correct": "正答は「誤っている」です。偽計行為は、詐術を用いて有価証券の相場を変動させる不公正取引です。事実に反する風説を流すのは説の流布（風説の流布）であり、同一ではありません。第138問の偽計行為・第308問の説の流布と接続します。",
        "explanation_point": "不公正取引4類型を「手段のキーワード1つ」ずつ付けて対比してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "310",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;バックオフィス;業務体制;standard",
        "stem": "バックオフィスは、証券会社の決済・記帳等の事務部門である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "バックオフィスは決済・記帳等の事務部門で、フロント（営業）と対比されます。",
        "explanation_summary": "バックオフィス＝事務部門。",
        "explanation_correct": "正答は「正しい」です。バックオフィスは、証券会社等の決済・記帳・事務処理を担う事務部門です。顧客への勧誘・受注を担うフロント（営業）と対比し、外務員の業務とバックオフィスの役割分担を整理します。",
        "explanation_point": "フロント・バックオフィス・ミドルオフィスを役割1行ずつの表にしてみましょう。",
        "explanation_choices": "",
    },
]
