# -*- coding: utf-8 -*-
"""二種実践演習 batch21：201〜210問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "201",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;TOB;公開買付け;standard",
        "stem": "TOBは、公開買付けの略称である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "TOB（Take Over Bid）は公開買付けの略称で、既発行株の買集め手続です。",
        "explanation_summary": "TOB＝公開買付け。",
        "explanation_correct": "正答は「正しい」です。TOB（Take Over Bid）は、公開買付けの略称で、不特定多数の株主から既発行の株式等を買い集める手続です。第163問の公開買付け・第151問の新規公開（IPO）とは目的が異なります",
        "explanation_point": "TOB・IPO・有価証券の引受けを「いつ・何を買うか」の3行表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "202",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;受益権;投資信託;standard",
        "stem": "受益権は、投資信託の受益者が信託財産に対して持つ権利である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "受益権は投信の持分に相当し、基準価額で価値が表示されます。",
        "explanation_summary": "受益権＝投信の持分。",
        "explanation_correct": "正答は「正しい」です。受益権は、投資信託の受益者が信託財産に対して持つ権利で、投信の「持分」に相当します。1口あたりの価値は基準価額で表示され、第9問の投資信託・第12問のETF（上場受益権）と接続します",
        "explanation_point": "受益権・受益証券・基準価額を「何を表すか」の1列で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "203",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;先渡取引;先物取引;standard",
        "stem": "先渡取引は、取引所で標準化されて取引される先物取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "先渡取引は店頭（OTC）の非標準化取引で、先物取引（取引所標準化）とは別です。",
        "explanation_summary": "先渡＝店頭・非標準。",
        "explanation_correct": "正答は「誤っている」です。先渡取引は、将来の一定期日に原資産の受渡しを約定する店頭（OTC）のデリバティブ取引です。先物取引は取引所で標準化されて取引されるものであり、同一ではありません",
        "explanation_point": "先渡取引・先物取引・スワップ取引を「取引の場／標準化」の2列で比較してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "204",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;ストップ高;値幅制限;standard",
        "stem": "ストップ高は、値幅制限の上限価格で買い注文のみが残る状態である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "ストップ高は値幅上限到達で売り手が見つからず買い注文のみ残る状態です。",
        "explanation_summary": "ストップ高＝上限・買いのみ。",
        "explanation_correct": "正答は「正しい」です。ストップ高は、値幅制限により決定された上限価格に達し、これ以上値上がりできず買い注文のみが残る状態です。ストップ安（下限・売りのみ）と対になり、第184問の値幅制限と接続します",
        "explanation_point": "ストップ高・ストップ安を「上限／下限」「買いのみ／売りのみ」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "205",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;成行注文;指値注文;standard",
        "stem": "成行注文は、指値注文と同一の注文である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "成行は価格不指定・最良気配、指値は指定価格条件付きで別類型です。",
        "explanation_summary": "成行≠指値。",
        "explanation_correct": "正答は「誤っている」です。成行注文は、価格を指定せず最良気配で約定する注文です。指値注文は指定価格以上（以下）でのみ約定する注文であり、同一ではありません。第195問の指値注文と対比して整理します",
        "explanation_point": "第195問と合わせ、成行・指値を2列比較表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "206",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;受渡;受渡日;standard",
        "stem": "受渡は、代金と有価証券を同時に交換する決済行為である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "受渡は約定後のDVP（代金引渡）決済で、代金と有価証券を同時交換します。",
        "explanation_summary": "受渡＝DVP決済。",
        "explanation_correct": "正答は「正しい」です。受渡は、有価証券売買において代金と有価証券を交換する決済行為で、DVP（代金引渡）方式により同時交付が原則です。約定（売買成立）とは段階が異なり、原則約定日から3営業日後（T+3）が受渡日です",
        "explanation_point": "約定・受渡・受渡日を「いつ何が起きるか」の3行フローにしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "207",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;投資運用業;投資信託;standard",
        "stem": "投資運用業は、投資信託の運用を業として行う金融商品取引業である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "投資運用業は投信委託者から運用を委託される投信運用の業態です。",
        "explanation_summary": "運用業＝投信運用。",
        "explanation_correct": "正答は「正しい」です。投資運用業は、投資信託の運用を業として行う金融商品取引業です。投信委託者から運用を委託され、第199問の投資一任業（個別一任契約）・第174問の投資助言業（助言のみ）と区別します",
        "explanation_point": "助言業・一任業・運用業を「契約／判断帰属」の3列で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "208",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;日本証券取引所;日本証券業協会;standard",
        "stem": "日本証券取引所は、日本証券業協会と同一の機関である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "日証取は取引所運営法人、日証協は自主規制機関で役割が異なります。",
        "explanation_summary": "日証取≠日証協。",
        "explanation_correct": "正答は「誤っている」です。日本証券取引所は、東京証券取引所等を運営する法人（取引所運営主体）です。日本証券業協会は自主規制機関で、外務員登録・勧誘規則等を担い、同一ではありません。第187問の日本証券業協会と対比します",
        "explanation_point": "日証取・日証協・金融庁を「取引所／自主規制／行政」の1行ずつ整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "209",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;場外取引;店頭売買;standard",
        "stem": "場外取引は、取引所金融商品市場外で行う取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "場外取引は市場外取引の総称で、店頭売買等が典型例です。",
        "explanation_summary": "場外＝市場外。",
        "explanation_correct": "正答は「正しい」です。場外取引は、取引所金融商品市場外で行う有価証券等の取引です。店頭売買等が典型例で、取引所での上場株売買とは規制・約定方式が異なります。第166問のPTSも取引所以外の売買市場として関連します",
        "explanation_point": "取引所・PTS・店頭売買を「売買の場」として3行で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "210",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;リスク許容度;適合性の原則;standard",
        "stem": "リスク許容度が高い顧客には、重要事項説明が不要である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "許容度は適合性判断の要素であり、37条の説明義務を免除しません。",
        "explanation_summary": "許容度高≠説明不要。",
        "explanation_correct": "正答は「誤っている」です。リスク許容度は、顧客が許容できるリスクの程度で、適合性の原則（第40条）の判断要素の一つです。許容度が高いからといって、重要事項説明（第37条）が不要になるわけではありません。第3問の適合性の原則と接続します",
        "explanation_point": "適合性（40条）・重要事項説明（37条）・リスク許容度を「判断／義務」の表にしてみましょう。",
        "explanation_choices": "",
    },
]
