# -*- coding: utf-8 -*-
"""二種実践演習 batch22：211〜220問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "211",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;投信委託者;投資信託;standard",
        "stem": "投信委託者は、投資信託を設定し運用方針等を定める者である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "投信委託者は信託契約を設定し運用方針の枠組みを定める投信の三役の一つです。",
        "explanation_summary": "委託者＝設定・方針。",
        "explanation_correct": "正答は「正しい」です。投信委託者は、投資信託を設定し、信託契約の内容・運用方針等を定める者です。日次運用は運用会社が担う典型があり、第207問の投資運用業・第9問の投資信託と接続します",
        "explanation_point": "投信委託者・投信受託者・運用会社を「三役」の1列ずつ書き分けてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "212",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;投信受託者;投信委託者;standard",
        "stem": "投信受託者は、投信委託者と同一の者である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "受託者は信託財産の保管・管理、委託者は設定・方針決定で役割が異なります。",
        "explanation_summary": "受託者≠委託者。",
        "explanation_correct": "正答は「誤っている」です。投信受託者は、信託財産を保管・管理する受託者（信託銀行等）です。投信委託者は投信を設定し運用方針等を定める者であり、同一ではありません。第211問の投信委託者・第202問の受益権とあわせて三役を整理します",
        "explanation_point": "委託者・受託者・受益者を投信の三役表にまとめてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "213",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;スワップ取引;デリバティブ;standard",
        "stem": "スワップ取引は、異なる条件のキャッシュフローを交換するデリバティブ取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "スワップは金利・通貨等のキャッシュフロー交換契約で、店頭取引が中心です。",
        "explanation_summary": "スワップ＝CF交換。",
        "explanation_correct": "正答は「正しい」です。スワップ取引は、金利・通貨・株式リターン等、異なる条件のキャッシュフローを当事者間で交換するデリバティブ取引です。第203問の先渡取引・先物取引とは性質が異なります",
        "explanation_point": "先渡・先物・スワップ・オプションを「本質」の1行ずつ比較表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "214",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;ストップ安;値幅制限;standard",
        "stem": "ストップ安は、値幅制限の下限価格で売り注文のみが残る状態である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "ストップ安は値幅下限到達で買い手が見つからず売り注文のみ残る状態です。",
        "explanation_summary": "ストップ安＝下限・売りのみ。",
        "explanation_correct": "正答は「正しい」です。ストップ安は、値幅制限により決定された下限価格に達し、これ以上値下がりできず売り注文のみが残る状態です。第204問のストップ高（上限・買いのみ）と対になり、第184問の値幅制限と接続します",
        "explanation_point": "第204問と合わせ、ストップ高・ストップ安の対句表を完成させてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "215",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;約定;受渡;standard",
        "stem": "約定は、受渡と同一の段階である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "約定は売買成立の確定、受渡はその後の代金・有価証券の決済です。",
        "explanation_summary": "約定≠受渡。",
        "explanation_correct": "正答は「誤っている」です。約定は、売買注文が成立し取引が確定した状態です。受渡は約定後に代金と有価証券を交換する決済行為であり、同一段階ではありません。第206問の受渡と「注文→約定→受渡」の3段フローで整理します",
        "explanation_point": "注文・約定・受渡を時系列の3行フローにしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "216",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;寄付;ザラバ方式;standard",
        "stem": "寄付は、取引所における始値形成の手続である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "寄付は市場開始時に注文を集合して価格（始値）を決める手続です。",
        "explanation_summary": "寄付＝始値形成。",
        "explanation_correct": "正答は「正しい」です。寄付は、取引所において売買注文を集合し価格を決定する始値形成の手続です。寄付後はザラバ方式等で継続取引が行われ、終値決定そのものではありません",
        "explanation_point": "寄付・ザラバ方式・板寄せ方式を「いつ／どう約定するか」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "217",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;先物取引の規制;デリバティブ;standard",
        "stem": "先物取引の規制は、派生商品取引に関する金商法上の規制である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "先物取引の規制はデリバ取引の登録・勧誘・適合性等を定める金商法上の規制群です。",
        "explanation_summary": "先物規制＝金商法デリバ規制。",
        "explanation_correct": "正答は「正しい」です。先物取引の規制は、派生商品（先物取引等）に関する金融商品取引法上の規制の総称で、業者の登録・顧客への説明・適合性の原則等が求められます。第3問の適合性の原則と接続します",
        "explanation_point": "金商法の業規制・取引所の証拠金規制を「規制主体」の2層で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "218",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;取引所金融商品市場;上場株式;standard",
        "stem": "取引所金融商品市場は、金融商品取引所が開設する売買市場である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "取引所金融商品市場は上場有価証券等の売買が行われる取引所の市場です。",
        "explanation_summary": "取引所市場＝上場売買場。",
        "explanation_correct": "正答は「正しい」です。取引所金融商品市場は、金融商品取引所が開設する有価証券等の売買市場で、上場株の通常取引が行われます。第209問の場外取引・第208問の日本証券取引所と接続します",
        "explanation_point": "取引所金融商品市場・場外取引・PTSを3市場表にまとめてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "219",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;信託業務;投信受託者;standard",
        "stem": "信託業務は、信託財産の管理・運用等を行う信託法上の業務である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "信託業務は受託者が信託財産を管理・運用する業務で、投信受託者も担います。",
        "explanation_summary": "信託業務＝信託財産管理。",
        "explanation_correct": "正答は「正しい」です。信託業務は、信託財産の管理・運用等を行う信託法上の業務です。投信受託者（信託銀行等）は投資信託の信託業務を担い、第212問の投信受託者・第150問の信託保全と接続します",
        "explanation_point": "信託業務・投信受託者・信託保全を「目的／担い手」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "220",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;元本欠損リスク;NISA;standard",
        "stem": "NISA口座内であれば、元本欠損リスクはない。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "NISAの非課税は税金の話であり、価格変動による元本欠損リスクは残ります。",
        "explanation_summary": "非課税≠元本保証。",
        "explanation_correct": "正答は「誤っている」です。元本欠損リスクは、投資商品の価格変動等により元本が減少し得るリスクです。NISA口座内であっても非課税は税金の話であり、値動きによる元本欠損リスクは残ります。第200問の分散投資・第210問のリスク許容度と接続します",
        "explanation_point": "NISA（非課税）・元本欠損リスク・信託保全を「税金／値動き／金銭保全」の3列で整理してみましょう。",
        "explanation_choices": "",
    },
]
