# -*- coding: utf-8 -*-
"""二種実践演習 batch14：131〜140問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "131",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;特定口座;NISA;standard",
        "stem": "特定口座で源泉徴収ありを選択した場合、原則として譲渡損益の確定申告が不要となる。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "特定口座は課税口座ですが源泉徴収ありなら原則確定申告不要、NISAの非課税とは別制度です。",
        "explanation_summary": "特定口座＝源泉ありで申告不要。",
        "explanation_correct": "正答は「正しい」です。特定口座は課税口座ですが、口座開設時に源泉徴収ありを選択すれば、原則として譲渡損益等の確定申告が不要になります。NISAの非課税制度とは別であり、譲渡益は課税対象です",
        "explanation_point": "NISA（非課税）・特定口座（課税・申告簡便）・一般口座（課税・申告必要）を3行で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "132",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;NISA;特定口座;standard",
        "stem": "NISAは、すべての金融商品を無制限に非課税で保有できる制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "NISAは対象商品・枠・上限が法令で定められ、すべての商品が非課税になるわけではありません。",
        "explanation_summary": "NISA＝枠・対象に制限。",
        "explanation_correct": "正答は「誤っている」です。NISAは配当・譲渡益を非課税とする税制優遇制度ですが、対象となる金融商品・投資枠・年間上限等が法令・制度で定められています。すべての金融商品を無制限に非課税で保有できるわけではなく、元本保証でもありません",
        "explanation_point": "新NISAのつみたて枠・成長枠・年間120万円上限を声に出して確認してみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "133",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;証拠金;保証金;standard",
        "stem": "証拠金は、信用取引において顧客が差し入れる保証金と同一である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "証拠金はデリバ取引の担保、保証金は信用取引の担保で、商品が異なる別制度です。",
        "explanation_summary": "証拠金≠保証金。",
        "explanation_correct": "正答は「誤っている」です。証拠金は先物・オプション等のデリバティブ取引で差し入れる担保です。信用取引の保証金（委託保証金）とは商品が異なる別制度であり、試験では両者を入れ替える肢が頻出です。第124問の保証金と対比して覚えましょう",
        "explanation_point": "「デリバ＝証拠金」「信用＝保証金」の2列ラベルを付け直してみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "134",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;代用証券;保証金;standard",
        "stem": "代用証券は、信用取引の保証金として時価に掛目を乗じて算入される有価証券である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "代用証券は現金の代わりに株式等を掛目付きで保証金に算入する制度です。",
        "explanation_summary": "代用証券＝掛目付き算入。",
        "explanation_correct": "正答は「正しい」です。代用証券とは、信用取引等で保証金（現金）に代えて差し入れる有価証券で、時価に掛目（評価率）を乗じて保証金額として算入されます。現金と同一評価ではなく、相場下落時は追証・強制決済リスクが高まり得ます",
        "explanation_point": "時価100万円×掛目80％＝80万円算入、の計算例を1回やってみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "135",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;制度信用取引;一般信用取引;standard",
        "stem": "制度信用取引は、金融商品取引所の制度に基づき行われる信用取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "制度信用は取引所の標準化された貸株制度に基づく信用取引で、一般信用と対比されます。",
        "explanation_summary": "制度信用＝取引所制度。",
        "explanation_correct": "正答は「正しい」です。制度信用取引は、金融商品取引所の制度（貸株制度等）に基づき行われる信用取引です。個別に貸株を調達する一般信用取引と対比され、試験では「標準型」として整理されます",
        "explanation_point": "制度信用と一般信用を、貸株の調達方法の1列で比較表にしてみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "136",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;空売り;信用取引;standard",
        "stem": "空売りは、保有していない有価証券を売り付ける取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "空売りは信用売り等で未保有の証券を売り、後で買い戻す取引で、現物売却とは異なります。",
        "explanation_summary": "空売り＝未保有の売付け。",
        "explanation_correct": "正答は「正しい」です。空売りとは、保有していない有価証券を売り付ける取引です。信用売り（制度信用・一般信用）や貸株を通じて行われ、後で買い戻して返済します。保有株の現物売却とは異なる点が定義の核心です",
        "explanation_point": "現物売却・信用買い・信用売り（空売り）を3行で書き分けられるか確認してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "137",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;臨時報告書;継続開示;standard",
        "stem": "臨時報告書は、重要事実が発生した場合に速やかに提出する継続開示書類である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "臨時報告書は都度開示の手段で、四半期報告書等の定期開示と役割が異なります。",
        "explanation_summary": "臨報＝重要事実の都度開示。",
        "explanation_correct": "正答は「正しい」です。臨時報告書は、重要事実が発生したときに速やかに内閣総理大臣に提出する継続開示書類です（金商法第24条の5）。四半期報告書・有価証券報告書等の定期開示では捕捉しきれない情報を都度開示します",
        "explanation_point": "第127問の四半期報告書と合わせ、定期開示と臨時開示の違いを整理してみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "138",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;偽計行為;不公正取引;standard",
        "stem": "偽計行為は、詐術を用いて有価証券の相場を変動させる不公正取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "偽計行為は不公正取引の一類型で、説の流布・相場操縦等と手段で区別します。",
        "explanation_summary": "偽計＝詐術で相場変動。",
        "explanation_correct": "正答は「正しい」です。偽計行為は、詐術（欺罔的手段）を用いて有価証券の相場を変動させる不公正取引の一類型です。説の流布（風説）、相場操縦、インサイダー取引等とあわせ、第119問の不公正取引の具体類型として整理します",
        "explanation_point": "不公正取引4類型を「手段のキーワード1つ」ずつ付けて対比してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "139",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;内部管理責任者;コンプライアンス;standard",
        "stem": "内部管理責任者は、金融商品取引業者の業務の適正を確保するため社内管理の責任を担う。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "内管責はコンプライアンス・利益相反管理等の社内管理体制の中核を担う役員等です。",
        "explanation_summary": "内管責＝社内管理の中核。",
        "explanation_correct": "正答は「正しい」です。内部管理責任者（内管責）は、金融商品取引業者等において業務の適正を確保するため、社内管理の責任を担う役員等です。コンプライアンス、利益相反管理、外務員の適切性の監督等が職務に含まれます",
        "explanation_point": "外務員・コンプライアンス・内部管理責任者の役割を3行で書き分けてみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "140",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;テロ資金供与;マネーロンダリング;standard",
        "stem": "テロ資金供与は、マネーロンダリングと完全に同一の概念である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "テロ資金供与とマネロンは別概念ですが、犯収法で併せて対策対象とされています。",
        "explanation_summary": "テロ資金≠マネロン。",
        "explanation_correct": "正答は「誤っている」です。テロ資金供与はテロ活動等への資金提供をいい、マネーロンダリング（犯罪収益の洗浄）とは別概念です。ただし犯罪収益移転防止法においては両方が対策対象とされ、証券会社も本人確認・疑わしい取引の届出等のAML手続を行います",
        "explanation_point": "第130問のマネロンと並べ、定義の違いと共通の対策法令を1枚にまとめてみましょう。",
        "explanation_choices": "",
    },
]
