# -*- coding: utf-8 -*-
"""二種実践演習 batch23：221〜230問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "221",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;コールオプション;オプション取引;standard",
        "stem": "コールオプションは、原資産を買う権利を付与するオプションである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "Callは原資産を買う権利で、Put（売る権利）・先物とは区別します。",
        "explanation_summary": "Call＝買う権利。",
        "explanation_correct": "正答は「正しい」です。コールオプションは、将来の一定期日までにあらかじめ定めた価格で原資産を買う権利を付与するオプションです。プットオプション（売る権利）・先物取引・ストックオプション（新株予約権）とは別制度です。",
        "explanation_point": "Call・Put・先物・SOを「権利／義務／対象」の4列比較表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "222",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;プットオプション;コールオプション;standard",
        "stem": "プットオプションは、原資産を買う権利を付与するオプションである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "Putは原資産を売る権利、Callは買う権利です。",
        "explanation_summary": "Put＝売る権利。",
        "explanation_correct": "正答は「誤っている」です。プットオプションは、あらかじめ定めた価格で原資産を売る権利を付与するオプションです。原資産を買う権利を付与するのはコールオプションであり、同一ではありません。第221問のコールオプションと対で整理します。",
        "explanation_point": "第221問と合わせ、Call＝Buy・Put＝Sellの対句を声に出して確認してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "223",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;損益通算;譲渡益課税;standard",
        "stem": "損益通算は、同一課税年度内で譲渡損失と譲渡益を相殺する制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "損益通算は課税口座の譲渡損益を同一年内で相殺する税制上の制度です。",
        "explanation_summary": "損益通算＝年内相殺。",
        "explanation_correct": "正答は「正しい」です。損益通算は、有価証券等の譲渡損失と譲渡益を同一課税年度内で相殺する税制上の制度です。NISA口座内の損益は非課税のため対象外であり、第183問の譲渡益課税・第131問の特定口座と接続します。",
        "explanation_point": "損益通算・繰越控除・NISA非課税を「対象口座」の1列で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "224",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;ザラバ方式;寄付;standard",
        "stem": "ザラバ方式は、寄付後に注文を順次約定させる方式である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "ザラバは寄付後も板に注文が載り価格・時間優先で順次約定します。",
        "explanation_summary": "ザラバ＝順次約定。",
        "explanation_correct": "正答は「正しい」です。ザラバ方式は、寄付で始値形成後、売買注文を順次約定させる取引所の約定方式です。板寄せ方式（一斉約定）とは対比され、第216問の寄付と接続します。",
        "explanation_point": "寄付・ザラバ方式・板寄せ方式を「約定のタイミング」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "225",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;受渡日;受渡;standard",
        "stem": "受渡日は、原則として約定日から3営業日後である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "上場株の受渡日は原則T+3（約定日から3営業日後）が定番です。",
        "explanation_summary": "受渡日＝T+3。",
        "explanation_correct": "正答は「正しい」です。受渡日は、有価証券売買の決済（受渡）を行う日で、原則として約定日から3営業日後（T+3）とされます。第206問の受渡・第215問の約定と「注文→約定→受渡（T+3）」で整理します。",
        "explanation_point": "約定日（T）・受渡日（T+3）・日計り取引の決済日を3行で比較してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "226",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;自己取引;取次;standard",
        "stem": "自己取引は、証券会社が他人の計算で行う売買である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "自己取引は自己の計算、取次は自己の名で他人の計算です。",
        "explanation_summary": "自己取引＝自己の計算。",
        "explanation_correct": "正答は「誤っている」です。自己取引は、金融商品取引業者が自己の計算で行う有価証券の売買です。他人の計算で行うのは取次であり、同一ではありません。第196問の媒介・代理・取次との4類型表で整理します。",
        "explanation_point": "自己取引・取次・代理・媒介を「誰の計算か」の1列で書き分けてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "227",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;形式主義の排除;みなし公募;standard",
        "stem": "形式主義の排除は、取引の実質を重視し形式だけで判断しない考え方である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "実質重視の原則で、形式上私募でも実質公募ならみなし公募等が適用されます。",
        "explanation_summary": "実質重視の原則。",
        "explanation_correct": "正答は「正しい」です。形式主義の排除は、取引の実質を重視し、形式的な要件だけで判断しない金融商品取引法上の考え方です。形式上私募でも実質公募ならみなし公募となる典型例と接続します。",
        "explanation_point": "形式主義の排除・みなし公募・私募をフロー図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "228",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;有価証券の売買等の規制;金融商品取引法;standard",
        "stem": "有価証券の売買等の規制は、金融商品取引法第2章に位置する規制である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "第2章は有価証券の売買等の規制、不公正取引は第4章等と章立てが異なります。",
        "explanation_summary": "売買規制＝第2章。",
        "explanation_correct": "正答は「正しい」です。有価証券の売買等の規制は、有価証券の売買等に関する金融商品取引法第2章の規制全般です。不公正取引（第4章）・業者規制等とは章立てが異なり、第167問の金融商品取引法全体像と接続します。",
        "explanation_point": "金商法の第2章・第4章・業者規制章を章番号付きで1枚にまとめてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "229",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;発行者以外の者による公開買付け;公開買付け;standard",
        "stem": "発行者以外の者による公開買付けは、発行会社以外の者が行う公開買付けである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "第三者TOBは発行会社以外の者が行う公開買付けで、MBOとは実施者が異なります。",
        "explanation_summary": "第三者TOB＝発行者以外。",
        "explanation_correct": "正答は「正しい」です。発行者以外の者による公開買付け（第三者TOB）は、発行会社以外の第三者が行う公開買付けです。発行者自身が行うMBOとは実施者が異なり、第201問のTOB・第163問の公開買付けと接続します。",
        "explanation_point": "第三者TOB・MBO・公開買付けを「実施者」の1列で比較してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "230",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;業務の適正な確保;コンプライアンス;standard",
        "stem": "業務の適正な確保は、投資家の投資損益を保証する義務である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "業務の適正な確保は業務運営の適正確保義務であり、損益保証ではありません。",
        "explanation_summary": "適正確保≠損益保証。",
        "explanation_correct": "正答は「誤っている」です。業務の適正な確保は、金融商品取引業者等が投資者保護のため業務運営の適正を確保すべきことをいう金商法上の要求です。投資家の投資損益を保証する義務ではなく、第38問のコンプライアンス・第189問の法令遵守体制と接続します。",
        "explanation_point": "業務の適正な確保・コンプライアンス・37条説明を「保証するか／体制か」の表にしてみましょう。",
        "explanation_choices": "",
    },
]
