# -*- coding: utf-8 -*-
"""二種実践演習 batch18：171〜180問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "171",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;成長投資枠;NISA;standard",
        "stem": "成長投資枠は、つみたて投資枠と合算して年間120万円まで非課税で保有できる。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "成長枠とつみたて枠は証券総合口座内で合算120万円が上限です。",
        "explanation_summary": "成長＋つみたて＝120万円。",
        "explanation_correct": "正答は「正しい」です。成長投資枠は新NISAの枠の一つで、つみたて投資枠と合算して年間120万円まで非課税で保有できます。第152問の証券総合口座・第132問のNISAと接続し、非課税枠であり元本保証ではありません。",
        "explanation_point": "つみたて枠・成長枠・120万円上限を1枚の図にまとめてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "172",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;一般口座;特定口座;standard",
        "stem": "一般口座は、特定口座と同一の制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "一般口座は特定口座以外で原則確定申告、特定口座は源泉徴収選択可です。",
        "explanation_summary": "一般口座≠特定口座。",
        "explanation_correct": "正答は「誤っている」です。一般口座は特定口座以外の証券口座で、有価証券の譲渡益について原則として確定申告による課税が必要です。特定口座は源泉徴収ありを選択すれば原則確定申告不要となる別制度であり、同一ではありません。",
        "explanation_point": "第131問の特定口座と合わせ、NISA・特定・一般の3口座を整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "173",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;ブックビルディング;有価証券の引受け;standard",
        "stem": "ブックビルディングは、投資家の需要調査に基づき発行価格等を決定する引受方式である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "BBはIPO等で需給調査により価格・割当を決める需要調査型の手続です。",
        "explanation_summary": "BB＝需給調査型引受。",
        "explanation_correct": "正答は「正しい」です。ブックビルディングは、有価証券の発行・売出しに際し、投資家からの需要調査に基づいて発行価格・割当数量等を決定する引受方式です。第165問の有価証券の引受け・第151問の新規公開（IPO）と接続します。",
        "explanation_point": "ブックビルディングとベストエフォート方式を2列で比較してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "174",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;投資助言契約;投資一任契約;standard",
        "stem": "投資助言契約において、最終的な売買判断は顧客が行う。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "助言契約は助言のみで、一任契約のように判断を委任するものではありません。",
        "explanation_summary": "助言契約＝判断は顧客。",
        "explanation_correct": "正答は「正しい」です。投資助言契約は、投資助言業に基づき投資判断の助言を受ける契約で、最終的な売買判断は顧客が行います。第155問の投資一任契約（判断を運用者に一任）とは区別します。",
        "explanation_point": "第145問・155問と合わせ、助言・一任・仲介の判断帰属を1列で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "175",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;日計り取引;信用取引;standard",
        "stem": "日計り取引は、当日中に売買を完結させる短期取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "日計りは信用取引で当日決済するデイトレードの典型で、短期リスクの説明が重要です。",
        "explanation_summary": "日計り＝当日完結。",
        "explanation_correct": "正答は「正しい」です。日計り取引は、当日中に売買を完結させる短期取引です。信用取引では建玉の当日決済が典型例で、適合性の原則に基づくリスク説明が求められます。",
        "explanation_point": "信用取引の「建玉→当日決済」の流れを声に出して確認してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "176",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;SOR;最良執行の原則;standard",
        "stem": "SORは、最良執行の原則と無関係である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "SORは複数市場を比較して最良執行を図る技術的手段です。",
        "explanation_summary": "SOR＝最良執行の手段。",
        "explanation_correct": "正答は「誤っている」です。SOR（スマートオーダールーティング）は、取引所・PTS等複数の売買市場を自動的に比較し、最良執行を図る仕組みです。第74問の最良執行の原則を技術的に実装する手段として位置づけられます。",
        "explanation_point": "最良執行の原則とSORを「義務」と「手段」の関係で1行ずつ書いてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "177",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;住基法;5％ルール;standard",
        "stem": "住基法は、大口株主の保有状況の開示に関する法律の通称である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "住基法は大量保有報告制度（5％ルール等）とセットで試験に出ます。",
        "explanation_summary": "住基法＝大口保有開示。",
        "explanation_correct": "正答は「正しい」です。住基法とは、大量保有の状況の開示に関する法律の通称で、大口株主の保有状況開示を定めます。第97問の5％ルール・第168問の変更報告書とあわせて大量保有報告制度として整理します。",
        "explanation_point": "住基法・5％ルール・大量保有報告書・変更報告書をフロー図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "178",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;価格変動率ルール;5％ルール;standard",
        "stem": "価格変動率ルールは、公開買付けの買付け価格と市場価格の乖離を制限するルールである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "価格変動率ルールはTOBの買付け価格の適正性確保で、5％ルール（保有割合）とは別です。",
        "explanation_summary": "価格変動率≠5％ルール。",
        "explanation_correct": "正答は「正しい」です。価格変動率ルールは、公開買付けにおいて買付け価格が直前の相場価格等から一定の割合を超えて設定されることを制限するルールです。第97問の5％ルール（保有割合の開示）とは規制対象が異なります。",
        "explanation_point": "5％ルール（保有割合）と価格変動率ルール（買付け価格）を2列で対比してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "179",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;任意買付け;公開買付け;standard",
        "stem": "任意買付けは、株主が任意に応募できる公開買付けの方式である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "任意買付けは応募自由、全部取得は残存株の強制取得と対比されます。",
        "explanation_summary": "任意買付＝応募自由。",
        "explanation_correct": "正答は「正しい」です。任意買付けは、公開買付けにおいて株主が任意に応募できる買付方式です。全部取得（残存株を強制取得する方式）と対比され、第169問の応募期間・第163問の公開買付けと接続します。",
        "explanation_point": "任意買付けと全部取得を「応募の自由」の1列で比較してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "180",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;倫理綱領;日本証券業協会;standard",
        "stem": "倫理綱領は、日本証券業協会が定める証券業界の倫理基準である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "倫理綱領は日証協の自主規制で、勧誘規則等の倫理的上位基準です。",
        "explanation_summary": "倫理綱領＝日証協倫理基準。",
        "explanation_correct": "正答は「正しい」です。倫理綱領は、日本証券業協会が定める証券業界の倫理基準で、外務員の行動規範の基盤です。金商法の法令とは別に、協会の自主規制として遵守が求められます。",
        "explanation_point": "金商法・勧誘規則・倫理綱領を「法令／実務規則／倫理」の3層で整理してみましょう。",
        "explanation_choices": "",
    },
]
