# -*- coding: utf-8 -*-
"""二種実践演習 batch29：281〜290問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "281",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;オルタナティブ投信;投資信託;standard",
        "stem": "オルタナティブ投信は、ヘッジファンド等を対象とする投資信託である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "オルタナティブ投信はヘッジ系運用を対象とする高リスク投信で、元本保証はありません。",
        "explanation_summary": "オルタナ＝ヘッジ系投信。",
        "explanation_correct": "正答は「正しい」です。オルタナティブ投信は、ヘッジファンド等のオルタナティブ運用を対象とする投資信託で、高リスク・高収益が典型とされます。第273問のファンド・オブ・ファンド・第241問の私募投信と区別し、元本保証ではありません",
        "explanation_point": "オルタナティブ投信・FoF・インデックス投信を「運用手法」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "282",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;転換社債;CB;standard",
        "stem": "CB（コンバーチブルボンド）は、転換社債の略称である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "CBは転換社債（Convertible Bond）の略称で、一定条件で株式に転換できる社債です。",
        "explanation_summary": "CB＝転換社債。",
        "explanation_correct": "正答は「正しい」です。CB（コンバーチブルボンド）は転換社債の略称で、一定の条件の下で社債を株式に転換できる社債です。第21問の転換社債・第11問の社債と接続し、転換前は社債・転換後は株式の2段階を整理します",
        "explanation_point": "CB・転換社債・社債・普通株式を「転換前／転換後」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "283",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;社債;有価証券;standard",
        "stem": "社債は、有価証券に該当しない。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "社債は金商法上の有価証券の典型例であり、株式・受益権等と並ぶ基本商品です。",
        "explanation_summary": "社債⊂有価証券。",
        "explanation_correct": "正答は「誤っている」です。社債は、会社が発行する債券で、金融商品取引法上の有価証券に該当します。第1問の有価証券・第19問の社債（五肢）と接続し、預金・保険は有価証券の範囲外である点も併せて整理します",
        "explanation_point": "有価証券・社債・株式・投資信託の受益権を「該当／非該当」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "284",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;プロの投資家;投資家区分;standard",
        "stem": "プロの投資家は、任意の個人投資家が口頭申告のみで該当する。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "プロの投資家は法定要件と所定の手続が必要で、口頭申告だけでは区分変更できません。",
        "explanation_summary": "プロ＝要件＋手続。",
        "explanation_correct": "正答は「誤っている」です。プロの投資家は、一定の要件を満たす投資家区分ですが、任意の個人が口頭申告のみで該当するわけではありません。法定要件と書面による申告・確認等の手続が必要です。第23問のプロの投資家・第30問の特定投資家と接続します",
        "explanation_point": "一般・特定・プロの区分変更に必要な手続を3列比較表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "285",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;私的勧誘;公開勧誘;standard",
        "stem": "私的勧誘は、不特定多数の投資家に対して行う勧誘である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "私的勧誘は特定の相手への勧誘で、不特定多数への勧誘は公開勧誘です。",
        "explanation_summary": "私的≠不特定多数。",
        "explanation_correct": "正答は「誤っている」です。私的勧誘は、特定の相手に対して行う販売等の勧誘です。不特定多数への勧誘は公開勧誘に当たり、私的勧誘とは区別されます。第96問の私的勧誘・第107問の私募と接続します",
        "explanation_point": "私的勧誘・公開勧誘・募集又は売出しを「相手方」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "286",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;契約締結前交付書面;書面交付;standard",
        "stem": "契約締結前交付書面は、契約締結後に交付する書面である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "契約締結前交付書面は、契約締結前に交付する書面で、締結時交付書面とは別です。",
        "explanation_summary": "前交付＝締結前。",
        "explanation_correct": "正答は「誤っている」です。契約締結前交付書面は、金融商品取引契約の締結前に投資家に交付する書面です。契約締結時交付書面は締結時に交付する別書面であり、交付タイミングが異なります。第14問の契約締結前交付書面・第20問の五肢と接続します",
        "explanation_point": "契約締結前交付書面・契約締結時交付書面・重要事項説明を「いつ交付か」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "287",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;財務諸表;有価証券報告書;standard",
        "stem": "財務諸表は、貸借対照表や損益計算書等を含む企業の財政状態・経営成績を示す書類群である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "財務諸表はBS・PL等の書類群で、有価証券報告書等の継続開示の中身を構成します。",
        "explanation_summary": "財務諸表＝BS・PL等。",
        "explanation_correct": "正答は「正しい」です。財務諸表は、企業の財政状態・経営成績等を示す書類群で、貸借対照表（BS）・損益計算書（PL）等が中心です。有価証券報告書・四半期報告書に記載・添付され、第88問の有価証券報告書と接続します",
        "explanation_point": "財務諸表・有価証券報告書・四半期報告書を「中身／書類」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "288",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;みなし公募;有価証券届出書;standard",
        "stem": "みなし公募であっても、有価証券届出書の提出は一切不要である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "みなし公募は公募扱いとなり、有価証券届出書の提出等の届出義務が生じます。",
        "explanation_summary": "みなし公募→届出必要。",
        "explanation_correct": "正答は「誤っている」です。みなし公募は、私募の法定要件を満たさない場合に公募とみなされる規制で、有価証券届出書の提出等の届出義務が生じます。第117問のみなし公募・第128問の少人数私募と接続します",
        "explanation_point": "私募要件OK／NG・みなし公募・有価証券届出書を分岐図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "289",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;臨時報告書;四半期報告書;standard",
        "stem": "臨時報告書は、四半期報告書と同一の定期開示書類である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "臨時報告書は重要事実発生時の都度開示、四半期報告書は定期開示です。",
        "explanation_summary": "臨報≠四半期。",
        "explanation_correct": "正答は「誤っている」です。臨時報告書は、重要事実が発生したときに速やかに提出する都度開示の書類です。四半期報告書は四半期ごとの定期開示書類であり、同一の定期開示書類ではありません。第137問の臨時報告書・第127問の四半期報告書と接続します",
        "explanation_point": "有価証券報告書・四半期報告書・臨時報告書を「定期／都度」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "290",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;流動性リスク;市場リスク;standard",
        "stem": "流動性リスクは、市場リスクと同一のリスクである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "流動性リスクは売買困難、市場リスクは価格変動による損失で、別類型です。",
        "explanation_summary": "流動性≠市場。",
        "explanation_correct": "正答は「誤っている」です。流動性リスクは、希望する価格・時期で売買できず損失を被るリスクです。市場リスクは価格変動による損失のリスクであり、同一ではありません。第280問の信用リスク・第270問のオペレーショナルリスクと4類型表で整理します",
        "explanation_point": "市場・信用・流動性・オペレの4リスクを定義1行ずつ書いてみましょう。",
        "explanation_choices": "",
    },
]
