# -*- coding: utf-8 -*-
"""二種実践演習 batch30：291〜300問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "291",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;受益証券;ETF;standard",
        "stem": "ETFは、受益権を上場して市場で売買される投資信託である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "ETFは受益権（受益証券）を上場し市場売買する投信で、一般投信の口座簿記とは異なります。",
        "explanation_summary": "ETF＝上場受益権。",
        "explanation_correct": "正答は「正しい」です。ETF（上場投資信託）は、投資信託の受益権を上場し、証券取引所で市場売買される商品です。一般投信は口座簿記が中心ですが、ETFは受益証券として売買されます。第41問の受益証券・第12問のETFと接続します。",
        "explanation_point": "受益証券・ETF・一般投信を「表示方法／売買場」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "292",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;国債;元本非保証;standard",
        "stem": "国債は、元本が絶対保証される。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "国債も価格変動・信用リスクがあり、元本が絶対保証されるわけではありません。",
        "explanation_summary": "国債≠元本保証。",
        "explanation_correct": "正答は「誤っている」です。国債は国が発行する債券ですが、満期償還や利子の受取権はあっても、価格変動リスクや発行者信用の変化により元本が絶対保証されるわけではありません。第31問の国債・第280問の信用リスクと接続します。",
        "explanation_point": "国債・社債・預金を「元本保証／非保証」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "293",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;インデックス投信;ETF;standard",
        "stem": "インデックス投信は、ETFと同一の商品である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "インデックス投信とETFは指数連動の点で似ますが、上場の有無等で別商品です。",
        "explanation_summary": "インデックス投信≠ETF。",
        "explanation_correct": "正答は「誤っている」です。インデックス投信は市場指数に連動する投信ですが、ETFは受益権を上場して売買する特殊な投信であり、同一の商品ではありません。第191問のインデックス投信・第12問のETFを「指数連動／上場有無」で対比します。",
        "explanation_point": "インデックス投信・ETF・アクティブ投信を3列比較表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "294",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;目論見書;開示;standard",
        "stem": "目論見書は、投資家に交付する開示書類である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "目論見書は投資家への交付が中心で、当局提出の届出書とは別です。",
        "explanation_summary": "目論見書＝投資家交付。",
        "explanation_correct": "正答は「正しい」です。目論見書は、有価証券の募集又は売出しの際に投資家（購入検討者）に交付される開示書類です。内閣総理大臣に提出する有価証券届出書とは提出先・交付先が異なります。第76問の目論見書・第87問の有価証券届出書と接続します。",
        "explanation_point": "届出書・目論見書・有価証券報告書を「提出先／交付先」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "295",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;不適当な勧誘;適合性の原則;standard",
        "stem": "顧客の状況に照らし明らかに不適当な勧誘は、禁止される。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "不適当な勧誘の禁止は適合性の原則等に基づき、投資家区分にかかわらず適用され得ます。",
        "explanation_summary": "不適当勧誘＝禁止。",
        "explanation_correct": "正答は「正しい」です。顧客の知識・経験・財産・目的に照らし明らかに不適当な勧誘は、適合性の原則（第40条）等により禁止されます。プロの投資家であっても適用され得ます。第33問の適合性の原則・第23問のプロの投資家と接続します。",
        "explanation_point": "適合性の原則・不適当な勧誘・重要事項説明を役割分担の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "296",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;代理;取次;standard",
        "stem": "代理は、本人の名で本人の計算において契約を締結する行為である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "代理は本人の名・本人の計算で契約し、効果は本人に帰属します。",
        "explanation_summary": "代理＝本人の名・計算。",
        "explanation_correct": "正答は「正しい」です。代理は、本人の名で本人の計算において契約を締結する民法上の法律行為です。効果は本人に帰属し、取次（自己の名・他人の計算）・媒介（当事者の名で仲介）と区別します。第44問の代理・第34問の取次と接続します。",
        "explanation_point": "代理・取次・媒介・自己取引を「誰の名／誰の計算」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "297",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;虚偽記載;不公正取引;standard",
        "stem": "虚偽記載の対象は、主に発行者が提出する法定開示書類である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "虚偽記載は有価証券届出書・有報等の法定開示書類が中心で、店頭販売資料とは別枠です。",
        "explanation_summary": "虚偽記載＝法定開示。",
        "explanation_correct": "正答は「正しい」です。虚偽記載は、有価証券届出書・有価証券報告書等、発行者が提出する法定開示書類への虚偽の重要な記載をいいます。証券会社の店頭販売資料とは規制枠組みが異なります。第89問の虚偽記載・第88問の有価証券報告書と接続します。",
        "explanation_point": "虚偽記載・重要事項説明・目論見書を「誰の書類か」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "298",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;適時開示;重要事実;standard",
        "stem": "適時開示は、上場会社が重要事実を速やかに公表する制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "適時開示は取引所規則等に基づき重要事実を速やかに市場へ伝える制度です。",
        "explanation_summary": "適時開示＝重要事実の公表。",
        "explanation_correct": "正答は「正しい」です。適時開示は、上場会社等が投資判断に影響を与える重要事実を、速やかに市場に公表する制度です。臨時報告書（当局提出）と役割分担しながら投資家保護を図ります。第78問の重要事実・第137問の臨時報告書と接続します。",
        "explanation_point": "適時開示・臨時報告書・有価証券報告書を「公表先／タイミング」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "299",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;外務員;金融商品取引業者;standard",
        "stem": "外務員は、金融商品取引業者の外務業務に従事する者である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "外務員は業者に所属し登録を受けて外務業務に従事する専門職です。",
        "explanation_summary": "外務員＝業者の外務担当。",
        "explanation_correct": "正答は「正しい」です。外務員は、金融商品取引業者の外務業務（勧誘・受注等）に従事する者で、第一種外務員・第二種外務員の区分があります。第6問の第二種外務員・第26問の第一種外務員と接続し、所属業者の登録範囲内で業務します。",
        "explanation_point": "外務員・第一種外務員・第二種外務員・金融商品取引業者を階層図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "300",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;市場リスク;リスク管理;standard",
        "stem": "市場リスクは、価格変動により損失を被るリスクである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "市場リスクは株価・金利等の価格変動による損失で、流動性リスク等と別類型です。",
        "explanation_summary": "市場リスク＝価格変動。",
        "explanation_correct": "正答は「正しい」です。市場リスクは、株価・金利・為替等の価格変動により損失を被るリスクです。流動性リスク（売買困難）・信用リスク・オペレーショナルリスクと区別し、第290問の流動性リスク・第270問のオペレーショナルリスクと4類型表で整理します。",
        "explanation_point": "市場・信用・流動性・オペレの4リスクを定義1行ずつ書いてみましょう。",
        "explanation_choices": "",
    },
]
