# -*- coding: utf-8 -*-
"""二種実践演習 batch35：341〜350問（〇×10）。standard 難度・Phase2 〇×350問 完結。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "341",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;株式分割;会社法;standard",
        "stem": "株式分割は、1株を複数株に分割する手続である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "株式分割は発行済株式数を増やし1株あたり株価を調整します。",
        "explanation_summary": "分割＝1株→複数株。",
        "explanation_correct": "正答は「正しい」です。株式分割は、1株を複数株に分割し、発行済株式数を増やすとともに1株あたりの株価を調整する手続です。株主の経済的持分は原則変わりません",
        "explanation_point": "株式分割・株式併合・株式分割の事前開示を整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "342",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;剰余金の配当;配当;standard",
        "stem": "剰余金の配当は、毎事業年度必ず支払われる。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "剰余金の配当は限度額内で決議により実施され、必ず毎期支払われるわけではありません。",
        "explanation_summary": "配当≠毎期義務。",
        "explanation_correct": "正答は「誤っている」です。剰余金の配当は配当可能限度額の範囲内で株主総会等の決議により実施されますが、毎事業年度必ず支払われるわけではありません。第153問の限度額・第73問の配当と接続します",
        "explanation_point": "配当・中間配当・剰余金の配当を決議機関で比較表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "343",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;譲渡制限株式;上場株式;standard",
        "stem": "譲渡制限株式は、上場株式と同様に市場で自由に売買できる。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "譲渡制限株式は会社承認が必要で、上場株のように自由売買できません。",
        "explanation_summary": "譲渡制限≠自由売買。",
        "explanation_correct": "正答は「誤っている」です。譲渡制限株式は定款により譲渡に会社の承認が必要とされた株式で、上場株式のように市場で自由に売買できるわけではありません。第103問の定義・第333問の上場株式と対比します",
        "explanation_point": "上場株式・譲渡制限株式を譲渡の自由度で比較してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "344",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;ディスクロージャー;開示;standard",
        "stem": "ディスクロージャーは、企業や金融商品に関する情報を開示することである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "ディスクロージャーは情報開示により投資家の適正な判断を支援します。",
        "explanation_summary": "開示＝ディスクロージャー。",
        "explanation_correct": "正答は「正しい」です。ディスクロージャーとは、企業や金融商品に関する情報を開示し、投資家の適正な判断を支援することです。第118問の継続開示・第294問の目論見書と接続します",
        "explanation_point": "ディスクロージャー・継続開示・適時開示を範囲の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "345",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;空売り;信用取引;standard",
        "stem": "空売りは、保有していない有価証券を売り付ける取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "空売りは信用売り・貸株等により行われ、理論上損失は拡大し得ます。",
        "explanation_summary": "空売り＝未保有で売付。",
        "explanation_correct": "正答は「正しい」です。空売りは、保有していない有価証券を売り付ける取引で、信用売りや貸株を通じて行われます。第335問の信用取引と接続し、現物売りとの区別を整理します",
        "explanation_point": "現物売り・空売り・信用売りを「保有の有無」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "346",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;保証金;信用取引;standard",
        "stem": "信用取引の保証金は、デリバティブ取引の証拠金と同一の制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "信用取引の保証金とデリバの証拠金は別制度です。",
        "explanation_summary": "保証金≠デリバ証拠金。",
        "explanation_correct": "正答は「誤っている」です。保証金は信用取引において顧客が証券会社に差し入れる担保です。デリバティブ取引の証拠金とは別制度であり、同一ではありません。第335問の信用取引と接続します",
        "explanation_point": "信用取引の保証金・委託証拠金・デリバ証拠金を区別する表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "347",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;変更報告書;大量保有報告;standard",
        "stem": "変更報告書は、大量保有報告書提出後に保有割合が1％以上変動した際に提出する。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "5％超の初回は大量保有報告書、以降1％変動で変更報告書です。",
        "explanation_summary": "変更報告＝1％変動。",
        "explanation_correct": "正答は「正しい」です。変更報告書は、大量保有報告書提出後に保有割合が1％以上変動した際に提出する報告書です。第168問の初回報告との区別・第108問の大量保有報告書と接続します",
        "explanation_point": "大量保有報告書・変更報告書をトリガー条件で対比表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "348",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;自己株券買付;自己株式;standard",
        "stem": "自己株券買付は、取得可能な株式数の上限なく無制限に行える。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "自己株買付には会社法・金商法上の上限や手続の制限があります。",
        "explanation_summary": "自己株買付≠無制限。",
        "explanation_correct": "正答は「誤っている」です。自己株券買付には、取得可能な株式数の上限等の制限があり、無制限に行えるわけではありません。第129問の上限・第91問の自己株式と接続します",
        "explanation_point": "自己株式・自己株券買付・取得上限を3行で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "349",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;半期報告書;四半期報告書;standard",
        "stem": "半期報告書は、現行制度でも上場会社が毎期提出する定期開示書類である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "半期報告書は四半期報告書制度導入により廃止されました。",
        "explanation_summary": "半期報告書＝廃止。",
        "explanation_correct": "正答は「誤っている」です。半期報告書は旧制度の6か月ごとの定期開示書類で、四半期報告書制度の導入により廃止されました。第149問の半期報告書・第127問の四半期報告書と接続します",
        "explanation_point": "半期（旧）・四半期（現行）・有報（年次）を頻度で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "350",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;犯罪収益移転防止法;犯収法;standard",
        "stem": "犯罪収益移転防止法は、証券会社等に本人確認・記録保存等を義務付ける。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "犯収法はマネロン・テロ資金供与防止のため本人確認等を義務付けます。",
        "explanation_summary": "犯収法＝本人確認等。",
        "explanation_correct": "正答は「正しい」です。犯罪収益移転防止法（犯収法）は、マネーロンダリング等を防止するため、金融機関・証券会社等に本人確認・記録保存・疑わしい取引の届出等を義務付ける法律です。第340問の記録保存と接続します",
        "explanation_point": "犯収法・取引時確認・疑わしい取引の届出をフロー図にしてみましょう。",
        "explanation_choices": "",
    },
]
