# -*- coding: utf-8 -*-
"""二種実践演習 batch17：161〜170問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "161",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;株主平等の原則;種類株式;standard",
        "stem": "株主平等の原則は、同種の株主は平等に扱われるべきという原則である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "株主平等の原則は会社法上の同種内平等で、種類株式の権利差異とは両立します。",
        "explanation_summary": "平等＝同種内。",
        "explanation_correct": "正答は「正しい」です。株主平等の原則は、同種の株主は会社法上平等に扱われるべきという原則です。同じ普通株式の株主間では配当・議決権等を不平等に扱えません。種類株式は定款で権利内容が異なるため、種類間の差異とは両立します。",
        "explanation_point": "普通株・優先株・種類株と「同種内平等」の2層表を書いてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "162",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;プライム市場;市場区分;standard",
        "stem": "プライム市場は、東京証券取引所の市場区分のうち最上位である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "プライムは2022年再編後の3区分（プライム・スタンダード・グロース）の最上位です。",
        "explanation_summary": "プライム＝最上位区分。",
        "explanation_correct": "正答は「正しい」です。プライム市場は、東京証券取引所の主市場で、2022年4月の市場再編後の3区分（プライム・スタンダード・グロース）のうち最上位です。大型・高流動性銘柄が上場し、第141問の上場株式として市場で売買されます。",
        "explanation_point": "プライム・スタンダード・グロースを厳しさ順に並べてみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "163",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;公開買付け;有価証券の引受け;standard",
        "stem": "公開買付けは、有価証券の引受けと同一の業務である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "TOBは既発行株の買集め、引受けは発行時の資金調達で目的が異なります。",
        "explanation_summary": "TOB≠引受け。",
        "explanation_correct": "正答は「誤っている」です。公開買付け（TOB）は、不特定多数から既発行の株式等を買い集める行為です。有価証券の引受けは、発行者から有価証券を引き受け投資家に販売する第一種業の業務であり、発行時の資金調達が目的で、同一ではありません。",
        "explanation_point": "第151問のIPO・第109問のTOB届出書と合わせ、発行時と買集めを分岐図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "164",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;貸株;信用取引;standard",
        "stem": "貸株は、信用売りのために借りる株式である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "信用売りでは未保有の株式を売るため貸株を借り、貸株料が発生します。",
        "explanation_summary": "貸株＝信用売り用。",
        "explanation_correct": "正答は「正しい」です。貸株とは、信用売りのために借りる株式です。保有していない株式を売る信用売りでは貸株を借りる必要があり、貸株料の支払いや貸株超過規制等が論点となります。第136問の空売りと接続します。",
        "explanation_point": "信用買い・信用売り・貸株の流れを3行で書き分けてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "165",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;有価証券の引受け;第一種金融商品取引業;standard",
        "stem": "有価証券の引受けは、第二種金融商品取引業の登録業務である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "引受けは第一種業の中核業務で、第二種業は主に媒介・代理です。",
        "explanation_summary": "引受け＝第一種業。",
        "explanation_correct": "正答は「誤っている」です。有価証券の引受けは、第一種金融商品取引業において、発行者から有価証券を引き受け販売する業務です。第二種金融商品取引業は主に媒介・代理であり、引受けは第一種業の領域です。",
        "explanation_point": "第一種業・第二種業の業務一覧を2列で比較表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "166",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;PTS;店頭売買;standard",
        "stem": "PTSは、私設取引システムの略称である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "PTSは取引所以外の電子的売買市場で、店頭有価証券等の取引に使われます。",
        "explanation_summary": "PTS＝私設取引システム。",
        "explanation_correct": "正答は「正しい」です。PTS（Proprietary Trading System）は、私設取引システムの略称で、金融商品取引所以外の電子的売買市場です。店頭有価証券や上場株の時間外取引等に利用され、第146問の店頭売買・第156問の店頭有価証券と関連します。",
        "explanation_point": "取引所・PTS・店頭売買を売買の場として3行で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "167",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;金融商品取引法;金商法;standard",
        "stem": "金融商品取引法は、有価証券等の取引と金融商品取引業を規律する法律である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "金商法は投資者保護と市場の公正を目的とする外務員試験の基本法です。",
        "explanation_summary": "金商法＝取引と業者の基本法。",
        "explanation_correct": "正答は「正しい」です。金融商品取引法（通称・金商法）は、有価証券等の取引と金融商品取引業の公正性を確保し、投資者保護を図るための基本法です。業者規制・開示制度・不公正取引の禁止等が柱となります。",
        "explanation_point": "金商法と金販法を「規律の対象」と「主な規制主体」で1行ずつ書き分けてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "168",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;変更報告書;5％ルール;standard",
        "stem": "変更報告書は、発行株式の5％を初めて超えて保有した際に提出する報告書である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "5％超の初回は大量保有報告書、以降1％以上変動で変更報告書です。",
        "explanation_summary": "5％初回＝大量保有報告書。",
        "explanation_correct": "正答は「誤っている」です。発行株式の5％を初めて超えて保有した際に提出するのは大量保有報告書です。変更報告書は、大量保有報告書提出後に保有割合が1％以上変動した際に提出する報告書であり、第97問の5％ルール・第108問の大量保有報告書と二段構えで整理します。",
        "explanation_point": "5％到達→大量保有報告書→1％変動→変更報告書の流れを図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "169",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;応募期間;公開買付け;standard",
        "stem": "公開買付けの応募期間は、原則20営業日以上とされる。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "応募期間はTOB手続の中核で、株主が売渡応募できる期間です。",
        "explanation_summary": "応募期間＝原則20営業日以上。",
        "explanation_correct": "正答は「正しい」です。応募期間は、公開買付けにおいて株主からの応募を受け付ける期間で、原則20営業日以上が要件です。公開買付届出書提出後、株主が売渡応募できる期間であり、第109問のTOB手続と接続します。",
        "explanation_point": "TOBの流れで「届出→応募期間→買付け完了」の順を確認してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "170",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;保証金信託;顧客分別金信託;standard",
        "stem": "保証金信託は、顧客分別金信託と同一の制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "保証金信託は信用取引の保証金用、分別金信託は顧客金銭保全用で目的が異なります。",
        "explanation_summary": "保証金信託≠分別金信託。",
        "explanation_correct": "正答は「誤っている」です。保証金信託は、信用取引の保証金を信託銀行等に信託する制度です。顧客分別金信託は顧客金銭の一般保全を目的とする信託保全の手段であり、目的が異なる別制度です。第150問の顧客分別金信託・第160問の譲渡性預金とあわせて整理します。",
        "explanation_point": "顧客分別金信託・譲渡性預金・保証金信託を目的別に3行で整理してみましょう。",
        "explanation_choices": "",
    },
]
