# -*- coding: utf-8 -*-
"""二種実践演習 batch16：151〜160問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "151",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;新規公開;公開買付け;standard",
        "stem": "新規公開は、公開買付け（TOB）と同一の制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "新規公開（IPO）は初上場の売出し、TOBは既上場株の買付けで別イベントです。",
        "explanation_summary": "IPO≠TOB。",
        "explanation_correct": "正答は「誤っている」です。新規公開（IPO）は、これまで上場していなかった株式を公開し不特定多数に売り出す初上場のイベントです。公開買付け（TOB）は既に上場している株式を買い集める制度であり、同一ではありません",
        "explanation_point": "第98問の公開買付け制度と並べ、IPOとTOBを「いつ・誰が・何をするか」で比較してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "152",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;証券総合口座;NISA;standard",
        "stem": "証券総合口座は、新NISAの非課税枠を統合した口座制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "証券総合口座はつみたて・成長枠を合算し年間120万円まで非課税保有できる新NISAの器です。",
        "explanation_summary": "総合口座＝新NISAの器。",
        "explanation_correct": "正答は「正しい」です。証券総合口座は、新NISA制度においてつみたて投資枠と成長投資枠を統合し、年間120万円まで非課税で保有できる個人向けの口座制度です。第132問のNISA・第131問の特定口座（課税）とは区別します",
        "explanation_point": "証券総合口座・NISA・特定口座の階層図を白紙から書いてみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "153",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;剰余金の配当;配当;standard",
        "stem": "剰余金の配当は、配当可能限度額の範囲内で実施される。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "剰余金の配当は会社法上の限度内で株主総会等の決議により行われます。",
        "explanation_summary": "配当＝限度額内。",
        "explanation_correct": "正答は「正しい」です。剰余金の配当は、会社の剰余金を原資として株主に行う配当で、配当可能限度額の範囲内で株主総会（または取締役会）の決議により実施されます。投信の分配金とは別制度であり、必ず支払われるわけではありません",
        "explanation_point": "第101問の中間配当と合わせ、配当の決議機関と限度額を整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "154",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;金融商品仲介業;登録金融機関;standard",
        "stem": "金融商品仲介業は、銀行等が証券会社を媒介して金融商品を販売する業態である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "仲介業は銀行・顧客・証券会社の三者構造で、登録金機とは役割が異なります。",
        "explanation_summary": "仲介業＝三者構造。",
        "explanation_correct": "正答は「正しい」です。金融商品仲介業は、銀行等が証券会社を媒介して金融商品を顧客に販売する金商法上の業態です。銀行窓口・顧客・証券会社の三者構造が核心で、第148問の登録金融機関（銀行が自ら証券業務）とは異なります",
        "explanation_point": "登録金機・金融商品仲介業・第一種業者を三者／二者で比較表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "155",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;投資一任契約;投資助言業;standard",
        "stem": "投資一任契約において、最終的な売買判断は顧客が行う。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "一任契約では運用判断を委託者に一任し、助言業とは判断の帰属が異なります。",
        "explanation_summary": "一任＝判断は運用者。",
        "explanation_correct": "正答は「誤っている」です。投資一任契約では、投資判断を委託者（運用者）に一任するため、最終的な売買判断は運用者側が行います。第145問の投資助言業（最終判断は顧客）とはこの点で区別します",
        "explanation_point": "第145問の助言業と並べ、「最終判断は誰か」の1列比較を声に出してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "156",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;店頭有価証券;店頭売買;standard",
        "stem": "店頭有価証券は、店頭で売買される有価証券である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "店頭有価証券は取引所以外で売買され、PTSでも取引可能です。",
        "explanation_summary": "店頭有価証券＝OTC商品。",
        "explanation_correct": "正答は「正しい」です。店頭有価証券は、金融商品取引所の市場以外（店頭）で売買される有価証券です。上場していない株式等を含む場合が多く、第146問の店頭売買・PTS取引と関連します",
        "explanation_point": "上場株式・店頭有価証券・店頭売買を商品と場の2軸で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "157",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;親子会社関係;連結決算;standard",
        "stem": "親子会社関係は、連結決算・開示に影響する。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "親会社が子会社を支配する関係は連結対象の範囲や開示内容に影響します。",
        "explanation_summary": "親子関係＝連結・開示。",
        "explanation_correct": "正答は「正しい」です。親子会社関係は、親会社が子会社を支配する関係をいい、連結決算の対象範囲や有価証券報告書等の連結情報の開示に影響します。企業グループ全体の財務・業績を投資家に伝えるうえで重要な概念です",
        "explanation_point": "親会社・子会社・連結子会社を1枚のグループ図にしてみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "158",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;内部統制報告書;有価証券報告書;standard",
        "stem": "内部統制報告書は、財務報告に関する内部統制の評価結果を記載する継続開示書類である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "内部統制報告書はJ-SOX関連の開示で、有価証券報告書と連動します。",
        "explanation_summary": "内統報告書＝財務報告の内統評価。",
        "explanation_correct": "正答は「正しい」です。内部統制報告書は、財務報告に関する内部統制の評価結果を記載する継続開示書類です。有価証券報告書に添付・記載される典型例で、経営者の評価と監査法人の監査報告がセットで問われます",
        "explanation_point": "有価証券報告書・内部統制報告書・四半期報告書を定期開示の年表に並べてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "159",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;訂正届出書;有価証券届出書;standard",
        "stem": "訂正届出書は、有価証券報告書の記載を訂正するための書類である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "訂正届出書は有価証券届出書等の訂正用で、有報の継続開示とは別類です。",
        "explanation_summary": "訂正届出＝届出書の訂正。",
        "explanation_correct": "正答は「誤っている」です。訂正届出書は、有価証券届出書等の記載内容を訂正するため提出する書類です。有価証券報告書（継続開示）の訂正書類とは別で、第87問の有価証券届出書の届出ファミリーに属します",
        "explanation_point": "届出書（新規公募）と有報（継続開示）の書類一覧を分けて整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "160",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;譲渡性預金;信託保全;standard",
        "stem": "譲渡性預金は、顧客金銭を銀行預金で保全する方式である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "譲渡性預金は信託保全の一手段で、顧客分別金信託とは仕組みが異なります。",
        "explanation_summary": "譲渡性預金＝銀行預金で保全。",
        "explanation_correct": "正答は「正しい」です。譲渡性預金は、顧客の金銭を銀行預金で保全する方式で、信託保全の手段の一つです。第150問の顧客分別金信託（信託方式）とは仕組みが異なり、いずれも顧客金銭の保護を目的とします",
        "explanation_point": "合算禁止・顧客分別金信託・譲渡性預金を金銭保全の3方式として整理してみましょう。",
        "explanation_choices": "",
    },
]
