# -*- coding: utf-8 -*-
"""二種実践演習 batch20：191〜200問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "191",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;インデックス投信;投資信託;standard",
        "stem": "インデックス投信は、市場指数に連動するよう運用される投資信託である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "インデックス投信はTOPIX等の指数追従を目的とするパッシブ運用の投信です。",
        "explanation_summary": "インデックス投信＝指数連動。",
        "explanation_correct": "正答は「正しい」です。インデックス投信は、日経平均株価・TOPIX等の市場指数に連動するよう設計・運用される投資信託です。アクティブ運用（指数超過を目指す）とは対比され、第9問の投資信託・第12問のETFと接続します",
        "explanation_point": "インデックス投信・ETF・アクティブ投信を「受益権／上場／運用目的」の3列で比較してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "192",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;分配金;投資信託;standard",
        "stem": "分配金は、投信から受益者に支払われる運用成果の金銭である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "分配金は利息・配当・売却益等の運用成果から受益者へ還元される金銭です。",
        "explanation_summary": "分配金＝運用成果の還元。",
        "explanation_correct": "正答は「正しい」です。分配金は、投資信託等の運用成果（利息・配当・売却益等）から受益者に支払われる金銭です。受取時に基準価額が下がる（除権）点が試験の定番で、解約金（元本返還）とは別概念です",
        "explanation_point": "分配金・基準価額・解約金を「何が動くか」の1列で書き分けてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "193",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;CB;転換社債;standard",
        "stem": "CBは、転換社債の略称である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "CB（コンバーチブルボンド）は転換社債の略称で、一定条件で株式に転換できる社債です。",
        "explanation_summary": "CB＝転換社債。",
        "explanation_correct": "正答は「正しい」です。CB（コンバーチブルボンド）は、一定条件で株式に転換できる社債の略称で、日本では転換社債と呼ばれることが多いです。第11問の社債・第2問の株式と接続し、転換前は社債として利払い・償還の権利を持ちます",
        "explanation_point": "社債・転換社債（CB）・普通株式を「債券性／転換権／株式性」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "194",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;サーキットブレーカー;値幅制限;standard",
        "stem": "サーキットブレーカーは、値幅制限と同一の制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "CB制度は急変時の一時停止、値幅制限は1日の価格帯制限で別制度です。",
        "explanation_summary": "CB≠値幅制限。",
        "explanation_correct": "正答は「誤っている」です。サーキットブレーカーは、急激な価格変動時に取引を一時停止する市場安定制度です。値幅制限（ストップ高・ストップ安）は1営業日の価格変動幅を制限する制度であり、同一ではありません。第184問の値幅制限と対比して整理します",
        "explanation_point": "値幅制限・ストップ高・サーキットブレーカーを「トリガー／効果」の3行表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "195",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;指値注文;成行注文;standard",
        "stem": "指値注文は、指定価格条件を満たさなければ約定しない場合がある。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "指値は価格優先の注文で、条件未達なら不成立となり得ます。",
        "explanation_summary": "指値＝不成立あり。",
        "explanation_correct": "正答は「正しい」です。指値注文は、指定した価格以上（売り）または以下（買い）でのみ約定する売買注文で、条件を満たさなければ約定しない場合があります。成行注文（価格不指定・最良気配で約定）と対比されます",
        "explanation_point": "指値注文・成行注文を「価格指定／約定の確実性」の2列で比較してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "196",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;媒介;代理;standard",
        "stem": "媒介は、契約の成立を仲介し当事者の名で行う法律行為である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "媒介は当事者の名で仲介し効果は本人に帰属、代理・取次・自己取引と区別します。",
        "explanation_summary": "媒介＝当事者の名で仲介。",
        "explanation_correct": "正答は「正しい」です。媒介は、契約の成立を仲介し、当事者の名で行う民法上の法律行為です。効果は本人に帰属し、代理（本人の名）・取次（自己の名・他人の計算）と区別します。第186問の仲介手数料の根拠概念でもあります",
        "explanation_point": "媒介・代理・取次・自己取引を4行表にして、誰の名で行うかを書き分けてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "197",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;リスク管理;重要事項説明;standard",
        "stem": "リスク管理は、顧客への重要事項説明のみで足りる。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "リスク管理は業者の内部管理体制で、37条の顧客向け説明とはレイヤーが異なります。",
        "explanation_summary": "内部管理≠37条説明。",
        "explanation_correct": "正答は「誤っている」です。リスク管理は、金融商品取引業者が業務リスクを識別・評価・制御する内部管理体制です。顧客への重要事項説明（第37条）とは別レイヤーであり、37条説明だけでは社内のリスク管理義務を果たせません。第189問の法令遵守体制と接続します",
        "explanation_point": "37条説明（顧客向け）・リスク管理（社内向け）・法令遵守体制を1列ずつ対象で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "198",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;株券等の大規模な買集め行為;公開買付け;standard",
        "stem": "株券等の大規模な買集め行為は、すべての株式取得行為に該当する。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "大規模買集めは一定要件を満たす買集め行為で、すべての取得が該当するわけではありません。",
        "explanation_summary": "大規模買集め≠全取得。",
        "explanation_correct": "正答は「誤っている」です。株券等の大規模な買集め行為は、一定の要件を満たす株式等の買集め行為で、公開買付け制度の適用対象となり得るものです。すべての株式取得が該当するわけではなく、第163問の公開買付け・第97問の5％ルール（大量保有報告）と目的が異なります",
        "explanation_point": "大規模買集め・公開買付け・5％ルールを「義務／届出書」の表にまとめてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "199",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;投資一任業;投資助言業;standard",
        "stem": "投資一任業は、投資助言業と同一の業態である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "一任業は裁量運用、助言業は助言のみで判断は顧客が行います。",
        "explanation_summary": "一任≠助言。",
        "explanation_correct": "正答は「誤っている」です。投資一任業は、投資一任契約に基づき顧客資産の運用を裁量で行う業態です。投資助言業は助言のみで最終判断は顧客が行い、同一ではありません。第155問の投資一任契約・第174問の投資助言契約と接続します",
        "explanation_point": "第174問・155問と合わせ、助言業・一任業・運用業の判断帰属を1列で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "200",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;分散投資;元本欠損リスク;standard",
        "stem": "分散投資により、元本が保証される。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "分散投資はリスク低減の考え方であり、元本保証や損失ゼロを意味しません。",
        "explanation_summary": "分散≠元本保証。",
        "explanation_correct": "正答は「誤っている」です。分散投資は、複数の資産・銘柄等に配分して特定資産への集中リスクを下げる考え方です。元本が保証されるわけではなく、元本欠損リスクは残ります。第3問の適合性の原則・投資信託（分散の手段）と接続します",
        "explanation_point": "分散投資・元本欠損リスク・投資信託を「リスク低減／元本保証」の2行表にしてみましょう。",
        "explanation_choices": "",
    },
]
