# -*- coding: utf-8 -*-
"""二種実践演習 batch28：271〜280問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "271",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;グロース市場;市場区分;standard",
        "stem": "グロース市場は、東証の成長企業向け市場区分である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "グロースは3区分のうち成長企業向けで、プライム・スタンダードより基準が緩い面があります。",
        "explanation_summary": "グロース＝成長枠。",
        "explanation_correct": "正答は「正しい」です。グロース市場は、東京証券取引所の成長企業向け市場区分で、2022年4月再編後のプライム・スタンダード・グロースの3区分のうち、基準が相対的に緩い枠です。第253問の市場区分・第162問のプライム市場と接続します",
        "explanation_point": "プライム・スタンダード・グロースを基準の厳しさ順に並べてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "272",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;スタンダード市場;プライム市場;standard",
        "stem": "スタンダード市場は、プライム市場と同一の市場区分である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "スタンダードは3区分の中核層で、プライムとは別の市場区分です。",
        "explanation_summary": "スタンダード≠プライム。",
        "explanation_correct": "正答は「誤っている」です。スタンダード市場は、東証3区分の中核層に位置する市場区分で、プライム市場（大型・高流動性）とは別です。上場基準はおおむねプライム＞スタンダード＞グロースの序列です",
        "explanation_point": "第271問と合わせ、3市場区分を1枚の表にまとめてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "273",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;ファンド・オブ・ファンド;投資信託;standard",
        "stem": "ファンド・オブ・ファンドは、他の投資信託に投資する投資信託である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "FoFは投信の投信で、下位・上位の二重の信託報酬が論点になります。",
        "explanation_summary": "FoF＝投信の投信。",
        "explanation_correct": "正答は「正しい」です。ファンド・オブ・ファンド（FoF）は、他の投資信託に投資する投資信託です。多層の信託報酬が発生する構造であり、第9問の投資信託・第243問の純資産総額と接続します",
        "explanation_point": "FoF・投資信託・信託報酬を「入れ子構造」の図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "274",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;ハイフリークエンシートレーディング;アルゴリズム取引;standard",
        "stem": "ハイフリークエンシートレーディング（HFT）は、アルゴリズム取引の類型である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "HFTは超高頻度で注文を出すアルゴ取引の類型です。",
        "explanation_summary": "HFT⊂アルゴ取引。",
        "explanation_correct": "正答は「正しい」です。ハイフリークエンシートレーディング（HFT）は、超高頻度で大量の注文を出す取引手法で、アルゴリズム取引の類型です。第264問のアルゴリズム取引・第194問のサーキットブレーカーと接続します",
        "explanation_point": "アルゴリズム取引・HFT・SORを「速度／頻度」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "275",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;最良執行の原則;VWAP;standard",
        "stem": "最良執行の原則は、顧客の注文について価格・速度等で最良の条件を求める原則である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "最良執行は顧客注文の執行品質を確保する原則で、VWAP等が評価基準になります。",
        "explanation_summary": "最良執行＝執行品質。",
        "explanation_correct": "正答は「正しい」です。最良執行の原則は、金融商品取引業者が顧客の売買注文について、価格・速度・約定可能性等で最良の条件を求める原則です。第255問のVWAP・第254問のブロックトレードと執行品質の文脈で接続します",
        "explanation_point": "最良執行の原則・VWAP・ブロックトレードを執行判断の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "276",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;サーキットブレーカー;ストップ高;standard",
        "stem": "サーキットブレーカーは、株価が急変した際に取引を一時停止する制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "サーキットブレーカーは市場の急変時に取引を一時停止し、混乱を抑えます。",
        "explanation_summary": "CB＝取引停止。",
        "explanation_correct": "正答は「正しい」です。サーキットブレーカーは、株価が急激に変動した際に取引を一時停止する制度で、市場の混乱を抑える目的があります。第203問のストップ高・第204問のストップ安と接続します",
        "explanation_point": "サーキットブレーカー・ストップ高/安・値幅制限を「いつ止まるか」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "277",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;第一種少額電子募集取扱業;第一種金融商品取引業;standard",
        "stem": "第一種少額電子募集取扱業は、少額の電子募集取扱を行う第一種業である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "第一種少額はインターネット等による少額募集の取扱いに特化した第一種業です。",
        "explanation_summary": "第一種少額＝取扱。",
        "explanation_correct": "正答は「正しい」です。第一種少額電子募集取扱業は、インターネット等を用いた少額の電子募集取扱を行う第一種金融商品取引業です。第268問の第二種少額（媒介）・第25問の第一種金融商品取引業と対比します",
        "explanation_point": "第一種少額・第二種少額・第一種業を「取扱／媒介」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "278",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;ファンドレビュー;投信委託者;standard",
        "stem": "ファンドレビューは、基準価額を毎日算定する制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "ファンドレビューは投信委託者が運用状況を定期評価する制度で、基準価額算定とは別です。",
        "explanation_summary": "レビュー≠基準価額算定。",
        "explanation_correct": "正答は「誤っている」です。ファンドレビューは、投資信託の運用状況を定期的に評価し、継続可否等を判断する制度で、投信委託者が実施します。基準価額の毎日算定とは別制度であり、第211問の投信委託者・第42問の基準価額と接続します",
        "explanation_point": "ファンドレビュー・基準価額・投信委託者を「誰が何をするか」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "279",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;訴訟持株;株主代表訴訟;standard",
        "stem": "訴訟持株は、株主代表訴訟の提訴要件と接点のある株式保有である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "訴訟持株は株主代表訴訟等の提訴要件を満たすための株式保有です。",
        "explanation_summary": "訴訟持株＝提訴要件。",
        "explanation_correct": "正答は「正しい」です。訴訟持株は、訴訟を起こす目的で保有する株式で、株主代表訴訟の提訴要件（一定期間の継続保有等）と接点があります。第269問の株主代表訴訟・第2問の株式と接続します",
        "explanation_point": "訴訟持株・株主代表訴訟・5％ルールを「目的」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "280",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;信用リスク;リスク管理;standard",
        "stem": "信用リスクは、国債には存在しないリスクである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "国債も発行者の信用リスクはゼロではなく、元本非保証です。",
        "explanation_summary": "国債も信用リスクあり。",
        "explanation_correct": "正答は「誤っている」です。信用リスクは、取引相手の債務不履行や信用悪化により損失を被るリスクです。国債も元本保証ではなく発行者の信用状況に依存するため、信用リスクがゼロではありません。第31問の国債・第270問のオペレーショナルリスクと4類型表で整理します",
        "explanation_point": "市場・信用・流動性・オペレの4リスクを1枚にまとめてみましょう。",
        "explanation_choices": "",
    },
]
