# -*- coding: utf-8 -*-
"""二種実践演習 batch19：181〜190問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "181",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;REIT;投資信託;standard",
        "stem": "REIT投資家は、受益権を通じて不動産を間接的に投資する。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "REITは不動産を原資産とする上場投信で、投資家は受益権による間接投資です。",
        "explanation_summary": "REIT＝間接投資。",
        "explanation_correct": "正答は「正しい」です。REIT（不動産投資信託）は、不動産に投資し賃料収入等を分配する上場投資信託で、投資家は受益権を通じて間接的に不動産に投資します。不動産を直接所有するわけではなく、第12問のETF・第9問の投資信託と同様に市場で売買できます。",
        "explanation_point": "REIT・ETF・投資信託を「原資産（不動産／指数／有価証券）」の1列で比較してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "182",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;つみたてNISA;成長投資枠;standard",
        "stem": "つみたてNISAは、任意の個別株式を一括購入できる枠である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "つみたて枠は対象投信等の定額購入用で、個別株の一括購入は成長投資枠の論点です。",
        "explanation_summary": "つみたて≠個別株一括。",
        "explanation_correct": "正答は「誤っている」です。つみたてNISA（つみたて投資枠）は、毎月一定額で対象となる投資信託等を継続購入する枠です。任意の個別株式を一括購入するのは成長投資枠の論点であり、同一ではありません。第171問の成長投資枠・第152問の証券総合口座と接続します。",
        "explanation_point": "つみたて枠・成長枠・120万円上限を2列表にして、対象商品の違いを書き分けてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "183",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;譲渡益課税;NISA;standard",
        "stem": "NISA口座内で売却した譲渡益には、譲渡益課税はかからない。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "NISAは非課税枠のため、枠内の譲渡益は課税されません。特定・一般口座は課税対象です。",
        "explanation_summary": "NISA内＝非課税。",
        "explanation_correct": "正答は「正しい」です。NISA口座内で売却した譲渡益は非課税のため、譲渡益課税はかかりません。特定口座・一般口座では上場株式等の譲渡益に20.315％等が課されます。第131問の特定口座・第172問の一般口座とあわせて口座別の課税を整理します。",
        "explanation_point": "NISA・特定・一般の3口座について「譲渡益課税の有無」を1行ずつ書いてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "184",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;値幅制限;ストップ高;standard",
        "stem": "値幅制限は、金融商品取引法が直接定める制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "値幅制限は取引所の売買制度で、上限到達がストップ高・下限がストップ安です。",
        "explanation_summary": "値幅制限＝取引所制度。",
        "explanation_correct": "正答は「誤っている」です。値幅制限は、取引所において1営業日の価格変動幅を制限する売買制度です。金融商品取引法そのものではなく、取引所規程に基づく制度であり、上限到達をストップ高、下限到達をストップ安といいます。",
        "explanation_point": "値幅制限・ストップ高・サーキットブレーカーを「取引所制度」の1枚にまとめてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "185",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;ベストエフォート方式;有価証券の引受け;standard",
        "stem": "ベストエフォート方式は、引受人が売れ残りを買い取る引受方式である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "BE方式は売れ残りリスクを引受人が負う方式で、BB（需給調査手続）とは別概念です。",
        "explanation_summary": "BE＝売れ残買取。",
        "explanation_correct": "正答は「正しい」です。ベストエフォート方式は、募集・売出しの結果生じた売れ残りを引受証券会社が買い取る引受方式です。第173問のブックビルディング（需給調査に基づく手続）とは別概念で、第165問の有価証券の引受けと接続します。",
        "explanation_point": "第173問のブックビルディングとBE方式を「手続」と「売れ残リスク」の2列で比較してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "186",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;仲介手数料;重要事項説明;standard",
        "stem": "仲介手数料は、契約締結前の重要事項説明で開示する必要がある。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "媒介・取次の対価である仲介手数料は、第37条の重要事項説明で顧客に開示します。",
        "explanation_summary": "手数料＝37条で開示。",
        "explanation_correct": "正答は「正しい」です。仲介手数料は、有価証券売買等の媒介・取次に対する報酬で、契約締結前の重要事項説明（第37条）や契約締結前交付書面で顧客に開示する必要があります。投信の信託報酬とは別概念です。",
        "explanation_point": "仲介手数料・信託報酬・37条説明を「対象／開示タイミング」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "187",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;日本証券業協会;勧誘規則;standard",
        "stem": "日本証券業協会は、法律を制定する機関である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "日証協は金商法に基づく自主規制機関で、法律制定は国会の権限です。",
        "explanation_summary": "日証協＝自主規制。",
        "explanation_correct": "正答は「誤っている」です。日本証券業協会は、金融商品取引法に基づく証券業等の自主規制機関で、勧誘規則の制定・外務員登録・試験運営等を担います。法律を制定するのは国会であり、金融庁は行政監督、協会は自主規制と役割が異なります。第180問の倫理綱領も協会の規則です。",
        "explanation_point": "国会（立法）・金融庁（行政）・日証協（自主規制）を1行ずつ役割で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "188",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;業務部門分離;利益相反管理;standard",
        "stem": "業務部門分離は、利害が相反する業務を適切に分離する体制である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "相反業務の分離は利益相反防止の内部管理で、完全兼業禁止とは異なります。",
        "explanation_summary": "部門分離＝相反業務の分離。",
        "explanation_correct": "正答は「正しい」です。業務部門分離は、金融商品取引業者が利害関係が相反する業務を適切に分離する体制です。自社売買部門と顧客媒介部門の情報交流制限等が典型例で、第17問の分別管理（資産の混同防止）とは規制対象が異なります。",
        "explanation_point": "業務部門分離・分別管理・利益相反管理を「規制対象」の1列で比較してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "189",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;法令遵守体制;コンプライアンス;standard",
        "stem": "法令遵守体制は、外務員個人だけの義務である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "法令遵守体制は業者（会社）が整備する組織的義務で、個人遵守とはレイヤーが異なります。",
        "explanation_summary": "体制＝会社の義務。",
        "explanation_correct": "正答は「誤っている」です。法令遵守体制は、金融商品取引業者が法令・規則を確実に遵守するため整備する内部管理の仕組みです。主体は業者（会社）の組織的義務であり、外務員個人の遵守義務とはレイヤーが異なります。第38問のコンプライアンスと接続します。",
        "explanation_point": "法令遵守体制（会社）と外務員の遵守義務（個人）を2行で書き分けてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "190",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;暗号資産;元本欠損リスク;standard",
        "stem": "暗号資産は、円やドル等の法定通貨である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "暗号資産は金商法上の金融商品ですが法定通貨ではなく、元本保証もありません。",
        "explanation_summary": "暗号資産≠法定通貨。",
        "explanation_correct": "正答は「誤っている」です。暗号資産は、暗号技術等で取引される電子的財産で、金融商品取引法上の金融商品に該当しますが、円・ドル等の法定通貨ではありません。価格変動・元本欠損リスクがあり、第37条の重要事項説明が求められます。",
        "explanation_point": "暗号資産・預金・有価証券を「法定通貨か／元本保証か」の2列表にしてみましょう。",
        "explanation_choices": "",
    },
]
