# -*- coding: utf-8 -*-
"""二種実践演習 batch34：331〜340問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "331",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;記名式有価証券;上場株式;standard",
        "stem": "上場株式は、原則として記名式有価証券である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "上場株式は記名式が原則で、株主名簿に記載されます。",
        "explanation_summary": "上場株＝記名式原則。",
        "explanation_correct": "正答は「正しい」です。上場株式は、原則として記名式有価証券であり、株主名簿に権利者が記載されます。第111問の指名式譲渡・第121問の無記名式との区別と接続します。",
        "explanation_point": "記名式・無記名式・上場株式を譲渡方法の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "332",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;無記名式有価証券;上場株式;standard",
        "stem": "現代の上場株式は、無記名式有価証券が原則である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "上場株式は記名式が原則で、無記名式ではありません。",
        "explanation_summary": "上場株≠無記名原則。",
        "explanation_correct": "正答は「誤っている」です。現代の上場株式は記名式が原則であり、無記名式が原則ではありません。第121問の無記名式・第331問の記名式と接続します。",
        "explanation_point": "記名式・無記名式・上場株式を3列比較表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "333",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;上場株式;取引所;standard",
        "stem": "上場株式は、金融商品取引所で市場売買される株式である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "上場株式は取引所に上場し公開市場で売買されます。",
        "explanation_summary": "上場株＝取引所売買。",
        "explanation_correct": "正答は「正しい」です。上場株式は、金融商品取引所に上場し、公開市場で売買される株式会社の株式です。第92問の単元株式数・第103問の譲渡制限株式と対比します。",
        "explanation_point": "上場株式・譲渡制限株式・新規公開を流れ図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "334",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;募集又は売出し;公開勧誘;standard",
        "stem": "募集又は売出しは、有価証券の取得を勧誘する行為である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "募集又は売出しは引受業務の核心概念で、公募・私募に区分されます。",
        "explanation_summary": "募集・売出し＝取得勧誘。",
        "explanation_correct": "正答は「正しい」です。募集又は売出しは、有価証券の取得を勧誘する行為で、引受業務の核心概念です。第87問の有価証券届出書・第107問の私募と接続します。",
        "explanation_point": "募集又は売出し・公募・私募を分岐図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "335",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;信用取引;保証金;standard",
        "stem": "信用取引は、顧客が保証金を差し入れて行う売買取引である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "信用取引は保証金を差し入れ、借株・借金で売買する取引です。",
        "explanation_summary": "信用取引＝保証金＋借入。",
        "explanation_correct": "正答は「正しい」です。信用取引は、顧客が保証金を差し入れ、証券会社から借りた株式等を使って行う売買取引です。追証・強制決済のリスクがあり、現物取引とは別制度です。",
        "explanation_point": "現物取引・信用取引・デリバティブを「保証金／借入」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "336",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;金融サービス提供法;金サ法;standard",
        "stem": "金融サービス提供法は、銀行・保険・証券を横断する規制を定める法律である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "金サ法は金融サービス提供と利用環境整備を横断的に規律します。",
        "explanation_summary": "金サ法＝横断規制。",
        "explanation_correct": "正答は「正しい」です。金融サービス提供法（金サ法）は、銀行・保険・証券を横断して金融サービスの提供と利用環境の整備に関する規制を定める法律です。第47問の金商法との区別・第84問の金販法と接続します。",
        "explanation_point": "金商法・金サ法・金販法を3行で書き比べてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "337",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;有価証券届出書;募集;standard",
        "stem": "有価証券届出書は、有価証券の募集又は売出しの際に当局へ提出する書類である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "届出書は新規募集・売出しの事前届出で、有報とは別です。",
        "explanation_summary": "届出書＝募集時提出。",
        "explanation_correct": "正答は「正しい」です。有価証券届出書は、有価証券の募集又は売出しを行う際に内閣総理大臣に提出する書類です。第87問の継続開示との混同・第334問の募集又は売出しと接続します。",
        "explanation_point": "届出書・目論見書・有報を「いつ提出か」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "338",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;四半期報告書;臨時報告書;standard",
        "stem": "四半期報告書は、臨時報告書と同一の都度開示書類である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "四半期報告書は定期開示、臨時報告書は都度開示です。",
        "explanation_summary": "四半期≠臨報。",
        "explanation_correct": "正答は「誤っている」です。四半期報告書は四半期ごとの定期開示書類であり、臨時報告書は重要事実発生時の都度開示書類です。第127問の四半期報告書・第137問の臨時報告書と接続します。",
        "explanation_point": "有報・四半期報告書・臨時報告書を「定期／都度」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "339",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;公開買付け制度;TOB;standard",
        "stem": "公開買付け制度は、公開買付けについて届出・開示等を定める制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "TOB制度は届出・買付期間・価格変動率ルール等を定めます。",
        "explanation_summary": "TOB制度＝届出・開示。",
        "explanation_correct": "正答は「正しい」です。公開買付け制度は、公開買付け（TOB）について届出・開示等を定める制度です。第98問の5％ルールとの区別・第109問の公開買付届出書と接続します。",
        "explanation_point": "TOB・5％ルール・大量保有報告を制度目的で対比してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "340",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;記録保存;コンプライアンス;standard",
        "stem": "記録保存は、勧誘・取引等の記録を法定期間保存することである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "記録保存は金商法・犯収法・勧誘規則等に基づき義務付けられます。",
        "explanation_summary": "記録保存＝法定期間保存。",
        "explanation_correct": "正答は「正しい」です。記録保存は、勧誘・取引・本人確認等の記録を法定期間保存することです。金商法・犯罪収益移転防止法・勧誘規則等が根拠となり、外務員の日常業務と直結します。",
        "explanation_point": "記録保存の根拠法令をリストアップしてみましょう。",
        "explanation_choices": "",
    },
]
