# -*- coding: utf-8 -*-
"""二種実践演習 batch25：241〜250問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "241",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;私募投信;特定投資家;standard",
        "stem": "私募投信は、特定投資家等を対象に私募の方法で設定される投資信託である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "私募投信は公募投信と募集形態・勧誘規制が異なる投信商品です。",
        "explanation_summary": "私募投信＝限定募集。",
        "explanation_correct": "正答は「正しい」です。私募投信は、特定投資家・プロの投資家等を対象に、私募の方法で設定・運用される投資信託です。公募投信とは勧誘規制が異なり、有価証券の私募（発行方法）とは別概念として整理します。",
        "explanation_point": "公募投信・私募投信・有価証券の私募を「商品か発行か」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "242",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;MMF;投資信託;standard",
        "stem": "MMFは、現在も元本が保証される商品である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "MMFは短期金融商品に投資する投信で、元本保証はありません。",
        "explanation_summary": "MMF≠元本保証。",
        "explanation_correct": "正答は「誤っている」です。MMF（マネー・マネジメント・ファンド）は、コールローン等の短期金融商品に投資する投資信託です。かつて元本安定型として普及しましたが、規制変更後は純資産総額方式等に移行し、現在も元本保証はありません。",
        "explanation_point": "MMF・投資信託・元本非保証を「短期性／保証の有無」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "243",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;純資産総額;基準価額;standard",
        "stem": "純資産総額は、投資信託の信託財産を時価評価した総額である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "純資産総額はNAV総額で、受益権口数で割ると基準価額（1口あたり）になります。",
        "explanation_summary": "純資産総額＝NAV総額。",
        "explanation_correct": "正答は「正しい」です。純資産総額は、投資信託の信託財産を時価評価した総額（NAV総額）です。受益権口数で割ると基準価額（1口あたり）が得られ、第42問の基準価額・第192問の分配金と接続します。",
        "explanation_point": "純資産総額・基準価額・受益権口数を「総額÷口数」の式で整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "244",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;特別気配;板寄せ方式;standard",
        "stem": "特別気配は、板寄せで需給が均衡せず約定しない場合に表示される気配である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "特別気配は板寄せの需給不均衡時に次の約定可能価格等を示す気配です。",
        "explanation_summary": "特別気配＝需給不均衡。",
        "explanation_correct": "正答は「正しい」です。特別気配は、板寄せ方式で需給が均衡せず一斉約定が成立しない場合に表示される気配です。始値形成やストップ高・安接近時に見られ、第234問の板寄せ方式・第216問の寄付と接続します。",
        "explanation_point": "板寄せ方式・特別気配・ストップ高/安を寄付前後のフロー図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "245",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;立会外分売;ブロックトレード;standard",
        "stem": "立会外分売は、取引時間外の大口売買で届出が必要な制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "立会外分売は時間外執行で市場への影響を抑え、届出等の要件があります。",
        "explanation_summary": "立会外分売＝時間外・届出。",
        "explanation_correct": "正答は「正しい」です。立会外分売は、通常の立会時間外に大口の株式売買を行う制度で、板への大量注文による価格影響を抑える目的があります。取引所への届出等の要件が適用されます。",
        "explanation_point": "立会外分売・ブロックトレード・VWAPを「時間外か一括か」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "246",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;名義書換;株主名簿;standard",
        "stem": "名義書換は、株式の売買約定と同一の手続である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "名義書換は株主名簿の名義更新で、約定・受渡とは別の実務手続です。",
        "explanation_summary": "名義書換≠約定。",
        "explanation_correct": "正答は「誤っている」です。名義書換は、株主名簿に記載された名義（氏名等）を変更する手続で、記名式株式の譲渡後に必要となります。売買の約定・受渡とは別段階の実務手続であり、同一ではありません。",
        "explanation_point": "約定・受渡・名義書換を「取引の流れ」の3段階表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "247",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;認可金融商品取引業協会;日本証券業協会;standard",
        "stem": "認可金融商品取引業協会は、内閣総理大臣の認可を受けた自主規制団体である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "認可協会は金商法上の業協会で、日本証券業協会が代表例です。",
        "explanation_summary": "認可協会＝自主規制。",
        "explanation_correct": "正答は「正しい」です。認可金融商品取引業協会は、金融商品取引法に基づき内閣総理大臣の認可を受けた自主規制団体です。日本証券業協会（第187問）が代表例で、第239問の金融商品取引業協会（総称）の個別類型です。",
        "explanation_point": "金融商品取引業協会・認可協会・日本証券業協会・金融庁を3層図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "248",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;継続的能力;金融商品取引業者;standard",
        "stem": "継続的能力は、上場会社の継続開示と同一の概念である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "継続的能力は業者登録の維持要件、継続開示は発行会社の情報開示です。",
        "explanation_summary": "継続的能力≠継続開示。",
        "explanation_correct": "正答は「誤っている」です。継続的能力は、金融商品取引業者が継続して適正に業務を行う能力をいい、業者登録の審査・維持要件です。上場会社の継続開示（適時開示等）は発行会社の情報開示制度であり、同一ではありません。",
        "explanation_point": "継続的能力・金融商品取引業者・適時開示を「誰の要件か」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "249",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;通報者保護制度;コンプライアンス;standard",
        "stem": "通報者保護制度は、内部通報者への報復禁止等を定める制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "通報者保護は金商法上の内部通報体制の一環で、報復禁止・秘密保持が中心です。",
        "explanation_summary": "通報者保護＝報復禁止。",
        "explanation_correct": "正答は「正しい」です。通報者保護制度は、金融商品取引業者等の内部通報体制の一環で、内部通報者を解雇・降格等の不利益取扱いから保護する金商法上の制度です。第38問のコンプライアンス・第189問の法令遵守体制と接続します。",
        "explanation_point": "コンプライアンス・内部通報・通報者保護をフロー図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "250",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;勧誘方針;勧誘規則;standard",
        "stem": "勧誘方針は、証券会社が定め公表する勧誘に関する基本方針である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "勧誘方針は勧誘規則に基づき公表が求められる会社の上位指針です。",
        "explanation_summary": "勧誘方針＝公表義務。",
        "explanation_correct": "正答は「正しい」です。勧誘方針は、証券会社が勧誘に関する基本方針を定め公表するもので、日本証券業協会の勧誘規則に基づきます。第28問の顧客本位の業務運営・第3問の適合性の原則と整合する内容が期待されます。",
        "explanation_point": "勧誘方針・勧誘規則・適合性の原則を「方針→規則→個別勧誘」の表にしてみましょう。",
        "explanation_choices": "",
    },
]
