# -*- coding: utf-8 -*-
"""二種実践演習 batch32：311〜320問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "311",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;種類株式;優先株式;standard",
        "stem": "優先株式は、種類株式の一類型である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "優先株式は定款で権利内容が異なる種類株式の代表例です。",
        "explanation_summary": "優先株⊂種類株。",
        "explanation_correct": "正答は「正しい」です。種類株式は定款の定めにより内容が異なる複数種類の株式であり、優先株式はその代表的な一類型です。第82問の種類株式・第81問の優先株式と接続し、普通株・優先株・種類株の包含関係を整理します。",
        "explanation_point": "普通株・種類株・優先株の包含関係を図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "312",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;地方債;国債;standard",
        "stem": "地方債は、国債と発行者が同一である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "地方債は地方公共団体発行、国債は国発行で発行者が異なります。",
        "explanation_summary": "地方債≠国債。",
        "explanation_correct": "正答は「誤っている」です。地方債は地方公共団体が発行する債券であり、国債は国が発行する債券です。いずれも公社債・有価証券に該当しますが、発行者は異なります。第83問の地方債・第31問の国債を発行者で対比します。",
        "explanation_point": "国債・地方債・社債を発行者1列の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "313",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;自己株式;会社法;standard",
        "stem": "自己株式は、株式会社が自己の発行済株式を取得した株式である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "自己株式は自社取得株であり、議決権行使は原則制限されます。",
        "explanation_summary": "自己株＝自社取得株。",
        "explanation_correct": "正答は「正しい」です。自己株式は、株式会社が自己の発行済株式を取得した株式です。第91問の議決権制限と接続し、定義（自社取得）と権利行使（議決権なし）を分けて整理します。",
        "explanation_point": "自己株式の定義と議決権制限を2行メモにまとめてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "314",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;金販法;クーリング・オフ;standard",
        "stem": "金融商品の販売等に関する法律は、クーリング・オフ等を規定する。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "金販法は販売場面の消費者保護で、クーリング・オフ等を規定します。",
        "explanation_summary": "金販法＝クーリング・オフ等。",
        "explanation_correct": "正答は「正しい」です。金融商品の販売等に関する法律（金販法）は、金融商品の販売・勧誘における消費者保護を定める法律で、クーリング・オフ等を規定します。第84問の金商法との役割分担・第7問のクーリング・オフと接続します。",
        "explanation_point": "金販法・金商法を「クーリング・オフ／37条説明」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "315",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;投資目的;適合性の原則;standard",
        "stem": "投資目的の確認だけで、適合性の原則の要件をすべて満たす。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "適合性の原則は知識・経験・財産・目的等を総合的に確認します。",
        "explanation_summary": "目的だけでは不十分。",
        "explanation_correct": "正答は「誤っている」です。投資目的は適合性の原則（第40条）の判断要素の一つですが、知識及び経験・財産の状況等も併せて確認する必要があり、投資目的の確認だけで要件をすべて満たすわけではありません。第94問の投資目的・第104問の投資経験と接続します。",
        "explanation_point": "第40条の確認要素4つをリストアップしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "316",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;投資経験;適合性の原則;standard",
        "stem": "投資経験が豊富な顧客には、適合性の原則による確認が不要である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "経験が豊富でも適合性の原則による確認は必要です。",
        "explanation_summary": "経験豊富≠確認不要。",
        "explanation_correct": "正答は「誤っている」です。投資経験が豊富な顧客であっても、適合性の原則（第40条）による確認は必要です。プロの投資家であっても適用され得る点と接続し、第104問の投資経験・第284問のプロの投資家と整理します。",
        "explanation_point": "投資経験・プロの投資家・適合性の原則の関係を3行で書いてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "317",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;第一種外務員;第二種外務員;standard",
        "stem": "第一種外務員は、第二種外務員より広い外務業務に対応する種別である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "第一種外務員は第一種業に係る外務業務に対応し、第二種より範囲が広いです。",
        "explanation_summary": "一種外務員＞二種外務員。",
        "explanation_correct": "正答は「正しい」です。第一種外務員は第一種金融商品取引業に係る外務業務に従事する種別で、第二種外務員より広い外務業務に対応します。第26問の登録範囲・第6問の第二種外務員と接続し、種別と業者登録の二軸で整理します。",
        "explanation_point": "第一種外務員・第二種外務員・第一種業・第二種業を対応表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "318",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;重要事実;未公開重要事実;standard",
        "stem": "重要事実が公表された後も、必ず未公開重要事実として取り扱われる。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "公表済みの重要事実は未公開重要事実ではありません。",
        "explanation_summary": "公表後≠未公開。",
        "explanation_correct": "正答は「誤っている」です。重要事実が適時開示等で公表された後は、未公開重要事実ではなくなります。未公開重要事実はまだ市場に知られていない重要事実であり、第78問の重要事実・第36問の未公開重要事実と接続します。",
        "explanation_point": "重要事実・未公開重要事実・適時開示をタイムラインで整理してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "319",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;5％ルール;大量保有報告;standard",
        "stem": "5％ルールは、保有割合が1％変更されるごとに都度報告する制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "5％超の初回報告と1％変更報告は別の義務です。",
        "explanation_summary": "5％ルール≠1％変更報告。",
        "explanation_correct": "正答は「誤っている」です。5％ルールは発行株式5％超保有時の大量保有報告書提出義務の通称です。保有割合が1％変更されるごとの報告は変更報告書の義務であり、同一ではありません。第97問の5％ルールと接続し、初回報告と変更報告を対比します。",
        "explanation_point": "大量保有報告書・変更報告書をトリガー条件で対比表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "320",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;内部牽制;内部統制;standard",
        "stem": "内部牽制は、業務の誤り・不正を防ぐ社内チェックの仕組みである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "内部牽制は内部統制の構成要素で、誤り・不正防止の社内チェックです。",
        "explanation_summary": "内部牽制＝社内チェック。",
        "explanation_correct": "正答は「正しい」です。内部牽制は、金融商品取引業者等が業務の誤り・不正を防ぐための社内チェックの仕組みで、内部統制の構成要素です。第310問のバックオフィス・コンプライアンスと接続し、業務体制の三層を整理します。",
        "explanation_point": "内部牽制・内部監査・コンプライアンスを役割1行ずつの表にしてみましょう。",
        "explanation_choices": "",
    },
]
