# -*- coding: utf-8 -*-
"""二種実践演習 batch33：321〜330問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "321",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;有価証券;金商法第2条;standard",
        "stem": "株式・社債・投資信託の受益権は、有価証券に該当する典型例である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "金商法第2条の有価証券は株式・社債・受益権等が中心です。",
        "explanation_summary": "株・債・受益権＝有価証券。",
        "explanation_correct": "正答は「正しい」です。金融商品取引法第2条の有価証券には、株式・社債・投資信託の受益権等が典型例として含まれます。第1問の預金との区別・第11問の社債と接続します。",
        "explanation_point": "有価証券・預金・保険を「該当／非該当」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "322",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;社債券;社債;standard",
        "stem": "社債券は、会社が発行する社債を分割して表示した有価証券である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "社債券は社債の分割表示で、金銭債権（利息・償還）を表示します。",
        "explanation_summary": "社債券＝社債の分割表示。",
        "explanation_correct": "正答は「正しい」です。社債券は、会社が発行する社債を分割して表示した有価証券であり、金銭債権（利息・償還請求権）を表示します。第93問の株式との区別・第19問の社債（五肢）と接続します。",
        "explanation_point": "社債券・社債・株式を「権利内容」の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "323",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;配当;剰余金;standard",
        "stem": "配当は、株主に対する利益分配の制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "配当は剰余金の配当が典型で、株主への利益分配制度です。",
        "explanation_summary": "配当＝利益分配。",
        "explanation_correct": "正答は「正しい」です。配当は、株式会社が株主に対し利益を分配する制度で、剰余金の配当が典型例です。第73問の「毎期義務」誤解・第153問の剰余金の配当と接続します。",
        "explanation_point": "配当・剰余金の配当・投信の分配金を区別する表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "324",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;資産状況;適合性の原則;standard",
        "stem": "資産状況は、適合性の原則における判断要素の一つである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "資産状況（財産の状況）は第40条の判断要素です。",
        "explanation_summary": "資産状況＝40条要素。",
        "explanation_correct": "正答は「正しい」です。資産状況（財産の状況）は、顧客の金融資産・収入等の状況をいい、適合性の原則（第40条）の判断要素の一つです。第105問の無関係誤解と対比し、生活必需資金超の勧誘が不適当になり得る点も整理します。",
        "explanation_point": "第40条の4要素をリストアップしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "325",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;知識及び経験;適合性の原則;standard",
        "stem": "資産が多い顧客であれば、知識及び経験の確認は不要である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "資産が多くても知識及び経験の確認は必要です。",
        "explanation_summary": "資産多≠確認不要。",
        "explanation_correct": "正答は「誤っている」です。知識及び経験は適合性の原則（第40条）の判断要素であり、資産が多い顧客であっても確認を省略できるわけではありません。第114問の知識及び経験・第316問の投資経験と接続します。",
        "explanation_point": "資産状況・知識及び経験・投資目的を役割分担の表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "326",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;販売等の勧誘;適合性の原則;standard",
        "stem": "販売等の勧誘には、適合性の原則が適用される。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "販売等の勧誘は外務員の日常業務で、第40条等が適用されます。",
        "explanation_summary": "勧誘⊃40条適用。",
        "explanation_correct": "正答は「正しい」です。販売等の勧誘とは金融商品の購入・売却等を勧める行為全般であり、適合性の原則（第40条）・重要事項説明（第37条）等が適用されます。第96問の私的勧誘・第33問の適合性の原則と接続します。",
        "explanation_point": "販売等の勧誘・私的勧誘・公開勧誘を包含関係の図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "327",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;金融商品取引法;不公正取引;standard",
        "stem": "金融商品取引法は、不公正取引の禁止等も規定する。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "金商法は市場公正・投資者保護のため不公正取引の禁止等を規定します。",
        "explanation_summary": "金商法⊃不公正取引禁止。",
        "explanation_correct": "正答は「正しい」です。金融商品取引法は、有価証券等の取引と金融商品取引業を規律する基本法で、相場操縦・インサイダー取引・説の流布等の不公正取引の禁止も規定します。第167問の金商法・第119問の不公正取引と接続します。",
        "explanation_point": "金商法の柱（業者規制・開示・不公正取引禁止）を3行で書いてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "328",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;登録金融機関;銀行;standard",
        "stem": "登録金融機関は、銀行等が証券業務のため金融商品取引法に登録した機関である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "登録金機は銀行・信託銀行等の登録で、第一種業者とは業務範囲が異なります。",
        "explanation_summary": "登録金機＝銀行等の登録。",
        "explanation_correct": "正答は「正しい」です。登録金融機関は、銀行・信託銀行等が有価証券の売買等の証券業務を行うため、金融商品取引法に登録した機関です。第148問の第一種業者との区別・第15問の第二種業と接続します。",
        "explanation_point": "証券会社・登録金機・第二種業者を登録種別で比較表にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "329",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;大量保有報告制度;5％ルール;standard",
        "stem": "大量保有報告制度は、発行株式5％超保有時の報告義務を定める制度である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "5％超保有時に大量保有報告書の提出義務が生じます。",
        "explanation_summary": "大量保有＝5％超報告。",
        "explanation_correct": "正答は「正しい」です。大量保有報告制度は、上場会社の発行株式を5％を超えて保有した者に大量保有報告書の提出義務を課す制度です。第79問の提出義務者・第97問の5％ルール・第177問の住基法と接続します。",
        "explanation_point": "5％ルール・大量保有報告書・変更報告書をフロー図にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "330",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;モニタリング;コンプライアンス;standard",
        "stem": "モニタリングは、取引や業務を継続的に監視することである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "モニタリングはAML・コンプライアンス実務で継続監視を指します。",
        "explanation_summary": "モニタリング＝継続監視。",
        "explanation_correct": "正答は「正しい」です。モニタリングとは、取引や業務を継続的に監視することで、AML（マネーロンダリング対策）・コンプライアンスの実務で頻出です。第320問の内部牽制・犯収法の取引時確認と接続します。",
        "explanation_point": "モニタリング・内部牽制・内部監査を役割1行ずつの表にしてみましょう。",
        "explanation_choices": "",
    },
]
