# -*- coding: utf-8 -*-
"""二種実践演習 batch11：101〜110問（〇×10）。standard 難度・Phase2 拡充。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "101",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;中間配当;配当;standard",
        "stem": "中間配当は、株主総会の決議のみで実施できる。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "中間配当は定款の定めと取締役会決議等が必要で、株主総会のみでは足りません。",
        "explanation_summary": "中間配当≠株総のみ。",
        "explanation_correct": "正答は「誤っている」です。中間配当は事業年度の途中で行う配当ですが、定款で中間配当を定めた会社において、取締役会の決議等を経て実施します。期末配当のように株主総会の決議のみで実施できるわけではありません。配当可能限度額の範囲内である点は共通です。",
        "explanation_point": "期末配当と中間配当を、決議機関・タイミングの2列で比較表にしてみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "102",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;株式併合;株式分割;standard",
        "stem": "株式併合は、発行済株式数を増やす手続である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "株式併合は複数株を1株にまとめ株数を減らす手続で、株式分割とは逆方向です。",
        "explanation_summary": "併合＝株数減。",
        "explanation_correct": "正答は「誤っている」です。株式併合は、複数の株式を1株に併合し、発行済株式数を減らすとともに1株あたりの株価を調整する手続です。発行済株式数を増やすのは株式分割であり、併合とは逆方向の手続です。株主の経済的持分は原則変わりません。",
        "explanation_point": "2株→1株の併合例で、持株数と1株価格がどう変わるか数字で計算してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "103",
        "type": "marubatsu",
        "category": "金融商品・サービス",
        "tags": "二種;〇×;譲渡制限株式;上場株式;standard",
        "stem": "譲渡制限株式は、定款により譲渡に会社の承認が必要とされた株式である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "譲渡制限株式は定款で譲渡に会社承認が必要な株式で、非上場株でよく見られます。",
        "explanation_summary": "譲渡制限＝承認必要。",
        "explanation_correct": "正答は「正しい」です。譲渡制限株式は、定款の定めにより、株式の譲渡について会社の承認が必要とされた株式です。非上場株・クローズドカンパニーでよく見られ、上場株式のように市場で自由に売買できるわけではありません。",
        "explanation_point": "上場株式と譲渡制限株式を、譲渡の自由度で対比メモにまとめてみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "104",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;投資経験;適合性の原則;standard",
        "stem": "投資経験は、適合性の原則における判断要素の一つである。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "投資経験は第40条の適合性判断で、商品理解度を見る要素の一つです。",
        "explanation_summary": "投資経験＝40条の要素。",
        "explanation_correct": "正答は「正しい」です。投資経験とは、顧客の過去の投資経験をいい、商品理解度の判断材料として適合性の原則（金融商品取引法第40条）で確認される要素の一つです。現物のみの経験がある顧客への信用取引勧誘など、実務でも重視されます。",
        "explanation_point": "信用取引未経験の顧客に信用売りを勧める場面が、なぜ慎重判断になるか一言で説明してみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "105",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;資産状況;適合性の原則;standard",
        "stem": "資産状況の確認は、適合性の原則と無関係である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "資産状況は第40条の「財産の状況」に相当し、過剰投資の防止に用いられます。",
        "explanation_summary": "資産状況＝40条の要素。",
        "explanation_correct": "正答は「誤っている」です。資産状況（財産の状況）は、顧客の金融資産・収入等の状況をいい、適合性の原則（第40条）の判断要素の一つです。生活必需資金を超える勧誘は不適当になり得るため、適合性の原則と無関係ではありません。",
        "explanation_point": "40条の4要素（知識・経験・財産・目的）を、勧誘前ヒアリングの質問例と対応づけてみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "106",
        "type": "marubatsu",
        "category": "勧誘・販売規則",
        "tags": "二種;〇×;募集又は売出し;引受;standard",
        "stem": "募集又は売出しは、引受業務と無関係である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "募集又は売出しは有価証券の取得勧誘であり、引受業務の核心概念です。",
        "explanation_summary": "募集売出し＝引受の核心。",
        "explanation_correct": "正答は「誤っている」です。募集又は売出しとは、有価証券の取得を勧誘する行為で、引受業務の核心概念です。発行者から有価証券を引き受け、投資家に販売する流れの勧誘部分に当たり、引受業務と無関係ではありません。",
        "explanation_point": "IPOの流れを「引受→募集又は売出し→目論見書交付」の3語で並べてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "107",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;私募;公募;standard",
        "stem": "私募は、特定の投資家に対してのみ有価証券の取得勧誘を行う方法である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "私募は特定の投資家へのみ取得勧誘を行う方法で、公募とは手続が異なります。",
        "explanation_summary": "私募＝特定者への勧誘。",
        "explanation_correct": "正答は「正しい」です。私募とは、不特定多数ではなく、特定の投資家に対してのみ有価証券の募集又は売出しの勧誘を行う方法です。公募に比べ届出・開示要件が緩和される場合がありますが、法定要件を満たす必要があり、不備があるとみなし公募となる場合もあります。",
        "explanation_point": "知人5名への新株割当が私募か公募か、判断の軸を3つ書き出してみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "108",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;大量保有報告書;5％ルール;standard",
        "stem": "大量保有報告書は、対象上場会社が提出する報告書である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "2",
        "explanation": "大量保有報告書の提出義務者は株式の保有者であり、対象上場会社ではありません。",
        "explanation_summary": "大量保有報告書＝保有者提出。",
        "explanation_correct": "正答は「誤っている」です。大量保有報告書は、上場会社の発行株式を5％を超えて保有した者（保有者）が内閣総理大臣に提出する報告書です。対象となる上場会社が提出するものではなく、第79問・第97問と同じ論点です。",
        "explanation_point": "5％ルール関連の3書類（大量保有報告書・公開買付届出書・有価証券届出書）の提出者を一覧にしてみましょう。",
        "explanation_choices": "",
    },
    {
        "question_no": "109",
        "type": "marubatsu",
        "category": "金融商品取引法",
        "tags": "二種;〇×;公開買付届出書;TOB;standard",
        "stem": "公開買付届出書は、公開買付者がTOB開始時に提出する書類である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "公開買付届出書は公開買付者がTOB開始前に当局へ提出する核心書類です。",
        "explanation_summary": "TOB届出＝買付者提出。",
        "explanation_correct": "正答は「正しい」です。公開買付届出書は、公開買付者が公開買付け（TOB）を行う際に、内閣総理大臣に提出する必要がある書類です。買付けの条件・期間・対象株式等が記載され、少数株主保護のための開示手段となります。",
        "explanation_point": "TOBニュースを見たら、届出書・目論見書・買付期間の3点をチェックする習慣をつけてみてください。",
        "explanation_choices": "",
    },
    {
        "question_no": "110",
        "type": "marubatsu",
        "category": "その他法令・業務",
        "tags": "二種;〇×;顧客の金銭の合算禁止;信託保全;standard",
        "stem": "顧客の金銭の合算禁止は、複数顧客の預かり金銭を混同して管理してはならない原則である。",
        "choice_1": "正しい",
        "choice_2": "誤っている",
        "correct": "1",
        "explanation": "合算禁止は顧客間の金銭混同を防ぐ原則で、信託保全とあわせて金銭保護の柱です。",
        "explanation_summary": "合算禁止＝顧客間混同NG。",
        "explanation_correct": "正答は「正しい」です。顧客の金銭の合算禁止とは、金融商品取引業者が複数の顧客の預かり金銭を混同して管理してはならない原則をいいます。A顧客とB顧客の金銭を1つの口座に混ぜない、という顧客資産保護の基本ルールです。",
        "explanation_point": "金銭の合算禁止・信託保全・有価証券の分別管理を、対象資産別に3行で整理してみましょう。",
        "explanation_choices": "",
    },
]
