# -*- coding: utf-8 -*-
"""二種実践演習 batch6：51〜55問（五肢5）。standard 難度・Phase1 残り前半。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "51",
        "type": "single",
        "category": "金融商品・サービス",
        "tags": "二種;五肢;投資信託;受益権;standard",
        "stem": "投資信託に関する次の記述のうち、誤っているものはどれか。",
        "choice_1": "受益権は、金融商品取引法上の有価証券に該当する。",
        "choice_2": "委託会社は、運用の結果に関わらず、投資家の元本を保証する。",
        "choice_3": "多数の投資家の金銭を一括して運用する仕組みである。",
        "choice_4": "分配金の有無・額は、ファンドの運用状況等により変動し得る。",
        "choice_5": "一般投資家向けの販売では、重要事項説明等が必要となる場合がある。",
        "correct": "2",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "52",
        "type": "single",
        "category": "金融商品・サービス",
        "tags": "二種;五肢;株式;社債;standard",
        "stem": "株式に関する次の記述のうち、正しいものはどれか。",
        "choice_1": "株主は、会社に対する金銭債権者（貸主）である。",
        "choice_2": "株式会社が発行し、株主の権利を表示する有価証券である。",
        "choice_3": "配当は、毎年必ず同額が支払われる。",
        "choice_4": "満期に元本が償還される債券と同一の性質である。",
        "choice_5": "元本が保証され、価格変動リスクはない。",
        "correct": "2",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "53",
        "type": "single",
        "category": "勧誘・販売規則",
        "tags": "二種;五肢;適合性の原則;第40条;standard",
        "stem": "適合性の原則に関する次の記述のうち、最も適切でないものはどれか。",
        "choice_1": "顧客の知識・経験・財産・投資目的に照らして、勧誘の適否を判断する。",
        "choice_2": "金融商品取引法第40条に関連する勧誘の適正を求める規範である。",
        "choice_3": "重要事項説明を行えば、適合性による勧誘判断は不要である。",
        "choice_4": "顧客の状況に合わない勧誘を防ぐことを目的とする。",
        "choice_5": "外務員が窓口勧誘で実務に関わる論点である。",
        "correct": "3",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "54",
        "type": "single",
        "category": "勧誘・販売規則",
        "tags": "二種;五肢;自己責任原則;standard",
        "stem": "自己責任原則に関する次の記述のうち、誤っているものはどれか。",
        "choice_1": "投資の結果の損益は、原則として投資家が負担する。",
        "choice_2": "金融商品取引業者は、投資結果について損失を補填する義務がある。",
        "choice_3": "重要事項説明義務と両立する考え方である。",
        "choice_4": "元本保証のない商品の販売と接続する原則である。",
        "choice_5": "勧誘・販売の適正義務を否定するものではない。",
        "correct": "2",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "55",
        "type": "single",
        "category": "金融商品取引法",
        "tags": "二種;五肢;一般投資家;投資家区分;standard",
        "stem": "一般投資家に関する次の記述のうち、正しいものはどれか。",
        "choice_1": "一般投資家は、特定投資家・プロの投資家以外に当てはまる区分である。",
        "choice_2": "一般投資家には、書面交付等の保護規制が一切適用されない。",
        "choice_3": "一般投資家は、常に投資の知識・経験がない投資家に限られる。",
        "choice_4": "口頭の申告のみで、直ちに特定投資家へ変更できる。",
        "choice_5": "一般投資家は、最も保護規制が緩い区分である。",
        "correct": "1",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
]
