# -*- coding: utf-8 -*-
"""二種実践演習 batch7：56〜70問（五肢15）。standard 難度・Phase1 完了分。"""

QUESTIONS: list[dict[str, str]] = [
    {
        "question_no": "56",
        "type": "single",
        "category": "金融商品取引法",
        "tags": "二種;五肢;第二種外務員;外務員;standard",
        "stem": "第二種外務員に関する次の記述のうち、誤っているものはどれか。",
        "choice_1": "主として店頭における外務業務に従事する外務員種別である。",
        "choice_2": "第一種外務員と常に同一の業務範囲・権限を有する。",
        "choice_3": "所属する金融商品取引業者の登録業務の範囲内で行う。",
        "choice_4": "外務員資格試験の種別の一つである。",
        "choice_5": "窓口での商品説明・受注等と接続する職務イメージに近い。",
        "correct": "2",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "57",
        "type": "single",
        "category": "その他法令・業務",
        "tags": "二種;五肢;反社会的勢力排除;コンプライアンス;standard",
        "stem": "反社会的勢力排除に関する次の記述のうち、正しいものはどれか。",
        "choice_1": "金融機関等が、反社会的勢力との取引を排除する取組みである。",
        "choice_2": "投資の運用損失を顧客に補填するための制度である。",
        "choice_3": "本人確認制度と完全に同一の手続である。",
        "choice_4": "勧誘規制を不要にするための投資家区分制度である。",
        "choice_5": "有価証券の発行手続を簡略化するための制度である。",
        "correct": "1",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "58",
        "type": "single",
        "category": "その他法令・業務",
        "tags": "二種;五肢;顧客本位の業務運営;standard",
        "stem": "顧客本位の業務運営に関する次の記述のうち、最も適切でないものはどれか。",
        "choice_1": "顧客の最善の利益を最優先に考える業務運営の考え方である。",
        "choice_2": "日本証券業協会が掲げる業務運営の基本方針の一つである。",
        "choice_3": "投資結果について、業者が顧客の損失を保証する制度である。",
        "choice_4": "自己責任原則と矛盾するものではない。",
        "choice_5": "商品販売・勧誘のプロセス改善と接続する。",
        "correct": "3",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "59",
        "type": "single",
        "category": "金融商品・サービス",
        "tags": "二種;五肢;ETF;投資信託;standard",
        "stem": "ETF（上場投資信託）に関する次の記述のうち、誤っているものはどれか。",
        "choice_1": "受益権は有価証券に該当する。",
        "choice_2": "取引所において、日中に売買できる場面がある。",
        "choice_3": "非上場の投資信託と同様、1日1回の申込・解約のみで売買できる。",
        "choice_4": "インデックス（指数）に連動するタイプが多い。",
        "choice_5": "一般の投資信託と比べ、市場での売買がしやすい商品である。",
        "correct": "3",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "60",
        "type": "single",
        "category": "勧誘・販売規則",
        "tags": "二種;五肢;重要事項説明;第37条;standard",
        "stem": "重要事項説明に関する次の記述のうち、正しいものはどれか。",
        "choice_1": "顧客が投資判断を行うために必要な情報を提供する義務である。",
        "choice_2": "説明を行えば、投資結果を業者が保証できる。",
        "choice_3": "適合性の原則による勧誘判断を不要にする。",
        "choice_4": "金融商品取引法第40条が根拠である。",
        "choice_5": "リスクや手数料は説明対象に含まれない。",
        "correct": "1",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "61",
        "type": "single",
        "category": "金融商品取引法",
        "tags": "二種;五肢;第一種金融商品取引業;第二種業;standard",
        "stem": "第一種金融商品取引業に関する次の記述のうち、誤っているものはどれか。",
        "choice_1": "有価証券の引受けや自己の計算による売買等を行い得る。",
        "choice_2": "第二種金融商品取引業と常に同一の業務範囲である。",
        "choice_3": "金融商品取引業の登録区分の一つである。",
        "choice_4": "一種業と二種業は、業務範囲が異なる。",
        "choice_5": "二種受験者は、一種専用業務の区別を押さえる必要がある。",
        "correct": "2",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "62",
        "type": "single",
        "category": "金融商品取引法",
        "tags": "二種;五肢;相場操縦;インサイダー取引;standard",
        "stem": "相場操縦に関する次の記述のうち、最も適切でないものはどれか。",
        "choice_1": "虚偽の注文等により相場を人為的に動かす行為が典型例である。",
        "choice_2": "未公開重要事実を知って行う取引そのものが、相場操縦に該当する。",
        "choice_3": "金融商品取引法上の不公正取引の一類型である。",
        "choice_4": "市場の公正性・信頼性を害する行為として規制される。",
        "choice_5": "インサイダー取引とは類型が異なる。",
        "correct": "2",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "63",
        "type": "single",
        "category": "その他法令・業務",
        "tags": "二種;五肢;信託保全;分別管理;standard",
        "stem": "信託保全に関する次の記述のうち、正しいものはどれか。",
        "choice_1": "顧客の金銭を保護するための制度の一つである。",
        "choice_2": "投資の運用損失を顧客に補填する制度である。",
        "choice_3": "有価証券の発行手続を簡略化する制度である。",
        "choice_4": "分別管理と完全に同一の制度である。",
        "choice_5": "本人確認を不要にする制度である。",
        "correct": "1",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "64",
        "type": "single",
        "category": "金融商品・サービス",
        "tags": "二種;五肢;社債;株式;standard",
        "stem": "社債に関する次の記述のうち、誤っているものはどれか。",
        "choice_1": "会社が発行する債券であり、金銭債権を表示する有価証券である。",
        "choice_2": "満期に元本の償還を請求する権利を有する。",
        "choice_3": "株式と同一の権利内容であり、議決権が必ず付される。",
        "choice_4": "発行会社の信用状況により、支払不能となるリスクがある。",
        "choice_5": "利息（利子）の支払いが定められる場合がある。",
        "correct": "3",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "65",
        "type": "single",
        "category": "勧誘・販売規則",
        "tags": "二種;五肢;契約締結時交付書面;standard",
        "stem": "契約締結時交付書面に関する次の記述のうち、正しいものはどれか。",
        "choice_1": "契約締結時に、顧客に交付する書面に関する制度である。",
        "choice_2": "契約締結前にのみ交付でき、締結後は交付不要である。",
        "choice_3": "重要事項説明を行えば、交付は一切不要である。",
        "choice_4": "一般投資家には適用されず、特定投資家のみが対象である。",
        "choice_5": "投資結果を業者が保証する内容を記載する書面である。",
        "correct": "1",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "66",
        "type": "single",
        "category": "金融商品取引法",
        "tags": "二種;五肢;未公開重要事実;適時開示;standard",
        "stem": "未公開重要事実に関する次の記述のうち、誤っているものはどれか。",
        "choice_1": "投資者の投資判断に重要な影響を与える事実で、まだ公表されていないものをいう。",
        "choice_2": "適時開示によりすでに公表された重要事実も、未公開重要事実に含まれる。",
        "choice_3": "インサイダー取引規制の判断要素となる。",
        "choice_4": "開示義務者が適時開示等により公表する対象となり得る。",
        "choice_5": "公表済みか未公表かの区別が、規制適用の分岐点となる。",
        "correct": "2",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "67",
        "type": "single",
        "category": "その他法令・業務",
        "tags": "二種;五肢;本人確認;マネロン;standard",
        "stem": "本人確認に関する次の記述のうち、最も適切でないものはどれか。",
        "choice_1": "マネー・ローンダリング対策の一環として行われる。",
        "choice_2": "顧客の氏名・住所等を確認する手続である。",
        "choice_3": "口頭確認のみで十分であり、書面・記録は一切不要である。",
        "choice_4": "金融機関等が取引開始時等に実施する。",
        "choice_5": "反社会的勢力排除の取組みと併せて重要である。",
        "correct": "3",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "68",
        "type": "single",
        "category": "勧誘・販売規則",
        "tags": "二種;五肢;プロの投資家;投資家区分;standard",
        "stem": "プロの投資家に関する次の記述のうち、正しいものはどれか。",
        "choice_1": "一定の要件を満たす投資家区分の一つであり、保護規制が最も緩和される。",
        "choice_2": "すべての個人投資家が、申告不要で該当する。",
        "choice_3": "一般投資家と同一の書面交付要件が常に適用される。",
        "choice_4": "投資の知識・経験がない投資家に限られる区分である。",
        "choice_5": "特定投資家より保護規制が厳しい区分である。",
        "correct": "1",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "69",
        "type": "single",
        "category": "金融商品・サービス",
        "tags": "二種;五肢;転換社債;社債;standard",
        "stem": "転換社債に関する次の記述のうち、誤っているものはどれか。",
        "choice_1": "一定の条件の下で、社債を株式に転換できる社債である。",
        "choice_2": "社債の一種であり、有価証券に該当する。",
        "choice_3": "転換により、株主としての地位を取得し得る。",
        "choice_4": "普通の社債と常に同一の権利内容であり、転換の仕組みはない。",
        "choice_5": "株と債の性質を併せ持つ商品として整理される。",
        "correct": "4",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
    {
        "question_no": "70",
        "type": "single",
        "category": "金融商品取引法",
        "tags": "二種;五肢;金融商品取引業者;登録;standard",
        "stem": "金融商品取引業者に関する次の記述のうち、最も適切でないものはどれか。",
        "choice_1": "金融商品取引法の登録を受けて業務を行う業者である。",
        "choice_2": "有価証券の売買の媒介・代理等を行い得る。",
        "choice_3": "有価証券を発行した上場会社は、それだけで金融商品取引業者である。",
        "choice_4": "第一種業・第二種業等、登録業務の範囲が異なる。",
        "choice_5": "顧客資産の分別管理等の義務を負う。",
        "correct": "3",
        "explanation": "（patch で上書き）",
        "explanation_summary": "（patch）",
        "explanation_correct": "（patch）",
        "explanation_choices": "（patch）",
        "explanation_point": "（patch）",
    },
]
